using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.Text;
using IsoDoom.Map;
using IsoDoom.Wad;
using IsoDoom.Wad.Graphics;

namespace IsoDoom.Tools.SyntheticIwad;

/// <summary>
/// A small synthetic IWAD for running the WAD viewer check in CI (T1.6b),
/// where no id Software WAD is available. Everything in it is generated here
/// (procedural palettes, patterns and shapes), so it holds no id data and can
/// be built anywhere; the output is deterministic.
/// <para>
/// It identifies as shareware Doom (<c>E1M1</c>, no <c>E3M1</c>) and has at
/// least one lump of every <see cref="LumpKind"/>: <c>PLAYPAL</c> (14
/// palettes) and <c>COLORMAP</c> (34 maps); <c>PNAMES</c>, <c>TEXTURE1</c> and
/// <c>TEXTURE2</c> with a single-patch, a multi-patch (overlapping, clipped
/// at the edges), a masked and a non-128-high texture; wall patches in
/// <c>P_START</c>/<c>P1_START</c> with a duplicate name (the later copy wins,
/// the earlier one is overridden); flats in <c>F_START</c>/<c>F1_START</c>;
/// sprites in <c>S_START</c> with a fully rotated frame (mirrored pairs) and
/// two rotation-0 frames, plus a sprite lump no sprite uses; global graphics
/// (title, status bar, menu, font glyphs, with offsets and transparency); a
/// two-room map with a real BSP tree (see <c>BuildMap</c>); ENDOOM, GENMIDI, DMXGUS, MUS and MIDI music, DMX and PC
/// speaker sounds, a demo and a plain text lump.
/// </para>
/// </summary>
public static class SyntheticIwad
{
    public const string DefaultFileName = "isodoom-synthetic.wad";

    /// <summary>The IWAD's bytes.</summary>
    public static byte[] Build()
    {
        var w = new Writer();
        w.Lump("PLAYPAL", BuildPlaypal());
        w.Lump("COLORMAP", BuildColormap());
        w.Lump("ENDOOM", BuildEndoom());
        w.Lump("DEMO1", BuildDemo());
        BuildMap(w);
        w.Lump("TEXTURE1", BuildTextureLump(
            new Tex("BRICK1", 64, 64, false, (0, 0, 0)),
            new Tex("BRKPNL", 128, 128, false, (0, 0, 0), (64, 0, 1), (-32, 64, 0), (32, 64, 0), (96, 64, 0)),
            new Tex("GRATE", 64, 64, true, (0, 0, 2), (32, 0, 2)),
            new Tex("PANEL", 64, 72, false, (0, -8, 1))));
        w.Lump("TEXTURE2", BuildTextureLump(new Tex("WINFRAME", 32, 64, false, (0, 0, 2))));
        w.Lump("PNAMES", BuildPNames("WALLBRK", "WALLPNL", "WINDOW"));
        w.Lump("GENMIDI", BuildGenmidi());
        w.Lump("DMXGUS", Encoding.ASCII.GetBytes("# Synthetic test patch map\r\n0, 2, 1, 0, acpiano\r\n"));
        w.Lump("D_E1M1", BuildMus());
        w.Lump("D_INTRO", BuildMidi());
        w.Lump("DSPISTOL", BuildDmxSound());
        w.Lump("DPPISTOL", BuildPcSpeakerSound());
        w.Lump("README", Encoding.ASCII.GetBytes(
            "IsoDoom synthetic test IWAD. Generated by tools/SyntheticIwad for the WAD viewer check in CI.\n"
            + "All content is procedural; it contains no id Software data. Not a playable game.\n"));

        // Global graphics (found by structure, as the UI lumps are).
        w.Lump("TITLEPIC", EncodePatch(TitlePic()));
        w.Lump("STBAR", EncodePatch(StatusBar()));
        w.Lump("M_DOOM", EncodePatch(MenuLogo()));
        w.Lump("STCFN065", EncodePatch(Glyph(GlyphA)));
        w.Lump("STCFN066", EncodePatch(Glyph(GlyphB)));
        w.Lump("STCFN067", EncodePatch(Glyph(GlyphC)));

        w.Markers("S_START");
        Image troo = Arrow();
        w.Lump("TROOA1", EncodePatch(troo));
        w.Lump("TROOA2A8", EncodePatch(troo.Tinted(1)));
        w.Lump("TROOA3A7", EncodePatch(troo.Tinted(2)));
        w.Lump("TROOA4A6", EncodePatch(troo.Tinted(3)));
        w.Lump("TROOA5", EncodePatch(troo.Tinted(4)));
        w.Lump("BAR1A0", EncodePatch(Barrel(0)));
        w.Lump("BAR1B0", EncodePatch(Barrel(1)));
        w.Lump("XXXXA0", EncodePatch(Barrel(2))); // in no sprite name list: listed, but no sprite frame
        w.Markers("S_END");

        w.Markers("P_START", "P1_START");
        w.Lump("WALLBRK", EncodePatch(Bricks()));
        w.Lump("WALLPNL", EncodePatch(Panel(0)));
        w.Lump("WINDOW", EncodePatch(Window()));
        w.Lump("WALLPNL", EncodePatch(Panel(2))); // duplicate: this one wins, the first is overridden
        w.Markers("P1_END", "P_END");

        w.Markers("F_START", "F1_START");
        w.Lump("FLOOR1", Checker().Pixels);
        w.Lump("FLOOR2", Diagonal().Pixels);
        w.Lump("LAVA1", Waves().Pixels);
        w.Markers("F1_END", "F_END");
        return w.Build();
    }

    /// <summary>
    /// Checks that the IWAD loads as the viewer loads it and has what the viewer
    /// check is meant to exercise. Returns the problems found (empty when fine).
    /// </summary>
    public static List<string> Check(WadArchive wad)
    {
        var problems = new List<string>();
        IwadInfo info = IwadIdentification.D_IdentifyVersion(wad);
        if (info.GameMode != GameMode.shareware)
            problems.Add($"identifies as {info.GameMode}, expected shareware");
        GraphicsCatalog catalog = GraphicsCatalog.Load(wad);
        foreach (GraphicCategory c in Enum.GetValues<GraphicCategory>())
        {
            if (catalog.Count(c) == 0)
                problems.Add($"no {c} in the graphics catalog");
        }
        var kinds = new HashSet<LumpKind>();
        bool overridden = false;
        foreach (LumpEntry e in LumpDirectory.Build(wad))
        {
            kinds.Add(e.Kind);
            overridden |= e.IsOverridden;
        }
        foreach (LumpKind k in Enum.GetValues<LumpKind>())
        {
            if (!kinds.Contains(k))
                problems.Add($"no lump of kind {LumpDirectory.KindName(k)}");
        }
        if (!overridden)
            problems.Add("no overridden lump");
        try
        {
            Level map = Level.Load(wad, "E1M1");
            if (map.Nodes.Length < 2 || map.Sectors.Length < 2)
                problems.Add($"E1M1 has {map.Nodes.Length} nodes and {map.Sectors.Length} sectors, expected a BSP tree over several sectors");
        }
        catch (WadFormatException e)
        {
            problems.Add($"E1M1 does not load: {e.Message}");
        }
        return problems;
    }

    // ---- Palette ----
    // Palette 0 is a 8x8x4 RGB grid: index = r | g << 3 | b << 6 (r, g in 0..7, b in 0..3).
    // No component reaches 255, which leaves the viewer check's background colours free.

    private static int Index(int r, int g, int b) => r | g << 3 | b << 6;

    private static (int R, int G, int B) BaseColor(int i) => ((i & 7) * 36, ((i >> 3) & 7) * 36, (i >> 6) * 84);

    private static byte[] BuildPlaypal()
    {
        // 0: normal; 1-8: red (damage, berserk); 9-12: gold (pickup); 13: green (radiation suit), as st_stuff.c numbers them.
        var tints = new List<(int R, int G, int B, int Num, int Den)> { (0, 0, 0, 0, 1) };
        for (int k = 1; k <= 8; k++)
            tints.Add((255, 0, 0, k, 9));
        for (int k = 1; k <= 4; k++)
            tints.Add((215, 186, 69, k, 8));
        tints.Add((0, 255, 0, 1, 8));

        byte[] lump = new byte[Playpal.PaletteSize * tints.Count];
        for (int p = 0; p < tints.Count; p++)
        {
            (int tr, int tg, int tb, int num, int den) = tints[p];
            for (int i = 0; i < 256; i++)
            {
                (int r, int g, int b) = BaseColor(i);
                int o = p * Playpal.PaletteSize + i * 3;
                lump[o] = (byte)(r + (tr - r) * num / den);
                lump[o + 1] = (byte)(g + (tg - g) * num / den);
                lump[o + 2] = (byte)(b + (tb - b) * num / den);
            }
        }
        return lump;
    }

    private static byte[] BuildColormap()
    {
        // 0-31: darker in 32 steps; 32: inverted greyscale (invulnerability); 33: all black.
        byte[] lump = new byte[Colormap.MapSize * 34];
        for (int m = 0; m < 32; m++)
        {
            for (int i = 0; i < 256; i++)
            {
                int r = i & 7, g = (i >> 3) & 7, b = i >> 6;
                lump[m * 256 + i] = (byte)Index((r * (32 - m) + 16) / 32, (g * (32 - m) + 16) / 32, (b * (32 - m) + 16) / 32);
            }
        }
        for (int i = 0; i < 256; i++)
        {
            (int r, int g, int b) = BaseColor(i);
            int inv = 255 - (r * 3 + g * 6 + b) / 10; // 0..255
            lump[32 * 256 + i] = (byte)Index((inv * 7 + 127) / 255, (inv * 7 + 127) / 255, (inv * 3 + 127) / 255);
        }
        return lump;
    }

    // ---- Images ----

    private sealed class Image
    {
        public readonly int Width, Height, Left, Top;
        public readonly byte[] Pixels;
        public readonly bool[] Opaque;

        public Image(int width, int height, int left = 0, int top = 0)
        {
            Width = width;
            Height = height;
            Left = left;
            Top = top;
            Pixels = new byte[width * height];
            Opaque = new bool[width * height];
        }

        public void Set(int x, int y, int index)
        {
            Pixels[y * Width + x] = (byte)index;
            Opaque[y * Width + x] = true;
        }

        /// <summary>A copy with the blue level shifted by <paramref name="step"/> (wrapping), so each rotation looks different.</summary>
        public Image Tinted(int step)
        {
            var copy = new Image(Width, Height, Left, Top);
            for (int p = 0; p < Pixels.Length; p++)
            {
                if (Opaque[p])
                    copy.Set(p % Width, p / Width, (Pixels[p] & 63) | ((((Pixels[p] >> 6) + step) & 3) << 6));
            }
            return copy;
        }
    }

    private static Image Solid(int width, int height, Func<int, int, int> color, int left = 0, int top = 0)
    {
        var img = new Image(width, height, left, top);
        for (int y = 0; y < height; y++)
        {
            for (int x = 0; x < width; x++)
                img.Set(x, y, color(x, y));
        }
        return img;
    }

    private static Image Bricks() => Solid(64, 64, (x, y) =>
    {
        int row = y / 16, bx = (x + (row % 2) * 16) % 32;
        if (y % 16 == 15 || bx == 31)
            return Index(4, 4, 1); // mortar
        return Index(5 + (row + bx / 8) % 3, 1 + (y % 16) / 6, 0);
    });

    private static Image Panel(int hue) => Solid(64, 128, (x, y) =>
    {
        int edge = Math.Min(Math.Min(x, 63 - x), Math.Min(y % 64, 63 - y % 64));
        int level = edge < 2 ? 7 : edge < 4 ? 2 : 3 + (y % 64) / 22;
        return Index(level, level, hue + (edge < 2 ? 1 : 0));
    });

    private static Image Window()
    {
        var img = new Image(32, 64);
        for (int y = 0; y < 64; y++)
        {
            for (int x = 0; x < 32; x++)
            {
                bool frame = x < 4 || x >= 28 || y < 4 || y >= 60 || (x >= 15 && x <= 16) || (y >= 30 && y <= 33);
                if (frame)
                    img.Set(x, y, Index(1 + x % 3, 3, 2));
            }
        }
        return img;
    }

    private static Image Checker() => Solid(64, 64, (x, y) => ((x / 8 + y / 8) % 2 == 0) ? Index(6, 6, 2) : Index(2, 2, 1));

    private static Image Diagonal() => Solid(64, 64, (x, y) => Index((x + y) / 16, 7 - (x + y) / 18, (x / 16) % 4));

    private static Image Waves() => Solid(64, 64, (x, y) =>
    {
        int t = (x * 3 + Tri(y * 4)) % 64;
        return Index(7, t / 10, 0);
    });

    private static int Tri(int v) => Math.Abs(v % 64 - 32); // a triangle wave in integers

    private static Image TitlePic() => Solid(320, 200, (x, y) =>
    {
        // An isometric diamond grid over a vertical gradient.
        bool line = (x + 2 * y) % 32 < 2 || (x - 2 * y + 400) % 32 < 2;
        return line ? Index(7, 6, 1) : Index(y / 40, y / 50, 3 - y / 67);
    });

    private static Image StatusBar() => Solid(320, 32, (x, y) =>
    {
        bool box = x % 64 < 2 || y < 2 || y >= 30;
        return box ? Index(6, 6, 1) : Index(3, 3, 1 + (x / 64) % 2);
    });

    private static Image MenuLogo()
    {
        // A diamond outline with a transparent inside and outside, offsets as menu graphics have.
        var img = new Image(96, 40, -4, -2);
        for (int y = 0; y < 40; y++)
        {
            for (int x = 0; x < 96; x++)
            {
                int d = Math.Abs(x - 48) * 40 / 96 + Math.Abs(y - 20);
                if (d >= 14 && d <= 20)
                    img.Set(x, y, Index(7, d - 13, 0));
            }
        }
        return img;
    }

    private static readonly string[] GlyphA = { "..#..", ".#.#.", "#...#", "#####", "#...#", "#...#", "#...#" };
    private static readonly string[] GlyphB = { "####.", "#...#", "####.", "#...#", "#...#", "#...#", "####." };
    private static readonly string[] GlyphC = { ".###.", "#...#", "#....", "#....", "#....", "#...#", ".###." };

    private static Image Glyph(string[] rows)
    {
        var img = new Image(rows[0].Length, rows.Length);
        for (int y = 0; y < rows.Length; y++)
        {
            for (int x = 0; x < rows[y].Length; x++)
            {
                if (rows[y][x] == '#')
                    img.Set(x, y, Index(7, 7 - y / 2, 0));
            }
        }
        return img;
    }

    private static Image Arrow()
    {
        // Asymmetric (points right, notch at the top), so a mirrored rotation is visibly mirrored.
        var img = new Image(41, 56, 20, 52);
        for (int y = 0; y < 56; y++)
        {
            for (int x = 0; x < 41; x++)
            {
                bool head = x >= 20 && Math.Abs(y - 28) <= 40 - x;
                bool shaft = x < 20 && y >= 22 && y <= 34;
                bool notch = y < 6 && x > 26;
                if ((head || shaft) && !notch)
                    img.Set(x, y, Index(x / 6, 2 + y / 14, 1));
            }
        }
        return img;
    }

    private static Image Barrel(int frame)
    {
        var img = new Image(23, 32, 11, 30);
        for (int y = 0; y < 32; y++)
        {
            for (int x = 0; x < 23; x++)
            {
                bool rim = y < 3 || y >= 29;
                bool body = Math.Abs(x - 11) <= (rim ? 9 : 11);
                if (body)
                    img.Set(x, y, rim ? Index(4, 4, 2) : Index(1 + frame, 3 + (x + frame * 3) % 5, 0));
            }
        }
        return img;
    }

    /// <summary>Encodes a patch: header, column offsets, then each column's posts (opaque runs of up to 128 pixels).</summary>
    private static byte[] EncodePatch(Image img)
    {
        if (img.Height > 254)
            throw new ArgumentException("Tall patches need relative topdeltas; not generated here.");
        var body = new List<byte>();
        int dataStart = 8 + 4 * img.Width;
        int[] offsets = new int[img.Width];
        for (int x = 0; x < img.Width; x++)
        {
            offsets[x] = dataStart + body.Count;
            int y = 0;
            while (y < img.Height)
            {
                if (!img.Opaque[y * img.Width + x])
                {
                    y++;
                    continue;
                }
                int start = y;
                while (y < img.Height && y - start < 128 && img.Opaque[y * img.Width + x])
                    y++;
                body.Add((byte)start);
                body.Add((byte)(y - start));
                body.Add(0); // unused pad byte
                for (int p = start; p < y; p++)
                    body.Add(img.Pixels[p * img.Width + x]);
                body.Add(0); // unused pad byte
            }
            body.Add(0xFF);
        }
        byte[] lump = new byte[dataStart + body.Count];
        BinaryPrimitives.WriteInt16LittleEndian(lump, (short)img.Width);
        BinaryPrimitives.WriteInt16LittleEndian(lump.AsSpan(2), (short)img.Height);
        BinaryPrimitives.WriteInt16LittleEndian(lump.AsSpan(4), (short)img.Left);
        BinaryPrimitives.WriteInt16LittleEndian(lump.AsSpan(6), (short)img.Top);
        for (int x = 0; x < img.Width; x++)
            BinaryPrimitives.WriteInt32LittleEndian(lump.AsSpan(8 + 4 * x), offsets[x]);
        body.CopyTo(lump, dataStart);
        return lump;
    }

    // ---- Wall textures (r_data.c maptexture_t / mappatch_t) ----

    private sealed record Tex(string Name, int Width, int Height, bool Masked, params (int X, int Y, int Patch)[] Patches);

    private static byte[] BuildPNames(params string[] names)
    {
        byte[] lump = new byte[4 + 8 * names.Length];
        BinaryPrimitives.WriteInt32LittleEndian(lump, names.Length);
        for (int i = 0; i < names.Length; i++)
            Encoding.ASCII.GetBytes(names[i], lump.AsSpan(4 + 8 * i));
        return lump;
    }

    private static byte[] BuildTextureLump(params Tex[] textures)
    {
        var body = new List<byte>();
        int dirSize = 4 + 4 * textures.Length;
        byte[] dir = new byte[dirSize];
        BinaryPrimitives.WriteInt32LittleEndian(dir, textures.Length);
        for (int i = 0; i < textures.Length; i++)
        {
            Tex t = textures[i];
            BinaryPrimitives.WriteInt32LittleEndian(dir.AsSpan(4 + 4 * i), dirSize + body.Count);
            byte[] mt = new byte[22 + 10 * t.Patches.Length];
            Encoding.ASCII.GetBytes(t.Name, mt);
            BinaryPrimitives.WriteInt32LittleEndian(mt.AsSpan(8), t.Masked ? 1 : 0);
            BinaryPrimitives.WriteInt16LittleEndian(mt.AsSpan(12), (short)t.Width);
            BinaryPrimitives.WriteInt16LittleEndian(mt.AsSpan(14), (short)t.Height);
            BinaryPrimitives.WriteInt16LittleEndian(mt.AsSpan(20), (short)t.Patches.Length);
            for (int j = 0; j < t.Patches.Length; j++)
            {
                Span<byte> mp = mt.AsSpan(22 + 10 * j);
                BinaryPrimitives.WriteInt16LittleEndian(mp, (short)t.Patches[j].X);
                BinaryPrimitives.WriteInt16LittleEndian(mp[2..], (short)t.Patches[j].Y);
                BinaryPrimitives.WriteInt16LittleEndian(mp[4..], (short)t.Patches[j].Patch);
                BinaryPrimitives.WriteInt16LittleEndian(mp[6..], 1); // stepdir (unused)
            }
            body.AddRange(mt);
        }
        byte[] lump = new byte[dirSize + body.Count];
        dir.CopyTo(lump, 0);
        body.CopyTo(lump, dirSize);
        return lump;
    }

    // ---- Map: two rooms, three subsectors under two BSP nodes ----
    //
    //  (-128,128) v0 ---L0--- v1 (128,128) ---L4--- v4 (384,128)
    //       |                  |                       |
    //       L3   west room     L1   east room, north   L5      y = 0: partition of
    //       |    sector 0      |    subsector 2        |       node 0 (no linedef),
    //       |    subsector 0   v7 - - - - - - - - - -  v6      split vertices v6, v7
    //       |                  |    east room, south   |
    //       |                  |    subsector 1        |
    // (-128,-128) v3 ---L2--- v2 (128,-128) ---L6--- v5 (384,-128)
    //
    // L1 is two-sided (the east room is raised 16 and its ceiling 16 lower, so
    // the west side has upper and lower textures). Node 1 (the root) splits
    // along L1, node 0 splits the east room at y = 0, so the east subsectors
    // each have an edge with no seg on it, as real node builders make them.
    // Linedefs run clockwise around each room, so their right (front) sides face in.

    private static readonly short[] MapVertexes =
    {
        -128, 128, 128, 128, 128, -128, -128, -128, // v0-v3: west room
        384, 128, 384, -128,                        // v4, v5: east room
        384, 0, 128, 0,                             // v6, v7: where node 0's partition splits L5 and L1
    };

    // v1, v2, flags, special, tag, right side, left side (-1: none)
    private static readonly short[,] MapLinedefs =
    {
        { 0, 1, 1, 0, 0, 0, -1 }, // L0: west room north
        { 1, 2, 4, 0, 0, 1, 2 },  // L1: two-sided, west room in front, east room behind
        { 2, 3, 1, 0, 0, 3, -1 }, // L2: west room south
        { 3, 0, 1, 0, 0, 4, -1 }, // L3: west room west
        { 1, 4, 1, 0, 0, 5, -1 }, // L4: east room north
        { 4, 5, 1, 0, 0, 6, -1 }, // L5: east room east
        { 5, 2, 1, 0, 0, 7, -1 }, // L6: east room south
    };

    private static void BuildMap(Writer w)
    {
        w.Markers("E1M1");
        w.Lump("THINGS", Shorts( // x, y, angle, type, flags (all skills)
            0, 0, 90, 1, 7,           // player 1 start
            64, 64, 0, 2035, 7,       // barrel (BAR1)
            320, 64, 180, 3001, 7));  // imp (TROO), in the east room's north subsector
        var linedefs = new List<short>();
        for (int i = 0; i < MapLinedefs.GetLength(0); i++)
        {
            for (int j = 0; j < MapLinedefs.GetLength(1); j++)
                linedefs.Add(MapLinedefs[i, j]);
        }
        w.Lump("LINEDEFS", Shorts(linedefs.ToArray()));
        w.Lump("SIDEDEFS", Concat(
            Sidedef("-", "-", "BRICK1", 0),         // 0: L0
            Sidedef("PANEL", "PANEL", "-", 0),      // 1: L1 front (west room): upper and lower
            Sidedef("-", "-", "-", 1),              // 2: L1 back (east room)
            Sidedef("-", "-", "BRKPNL", 0, 32),     // 3: L2, with an x offset
            Sidedef("-", "-", "BRICK1", 0),         // 4: L3
            Sidedef("-", "-", "BRKPNL", 1),         // 5: L4
            Sidedef("-", "-", "BRICK1", 1, 0, 8),   // 6: L5, with a y offset
            Sidedef("-", "-", "BRKPNL", 1)));       // 7: L6
        w.Lump("VERTEXES", Shorts(MapVertexes));
        const short East = 0, North = 0x4000, West = unchecked((short)0x8000), South = unchecked((short)0xC000);
        w.Lump("SEGS", Shorts( // v1, v2, angle (BAM >> 16), linedef, side (0 front, 1 back), offset along the linedef side
            0, 1, East, 0, 0, 0,     // seg 0-3: subsector 0, the west room
            1, 2, South, 1, 0, 0,
            2, 3, West, 2, 0, 0,
            3, 0, North, 3, 0, 0,
            6, 5, South, 5, 0, 128,  // seg 4-6: subsector 1, the east room's south half
            5, 2, West, 6, 0, 0,
            2, 7, North, 1, 1, 0,
            7, 1, North, 1, 1, 128,  // seg 7-9: subsector 2, the east room's north half
            1, 4, East, 4, 0, 0,
            4, 6, South, 5, 0, 0));
        w.Lump("SSECTORS", Shorts(4, 0, 3, 4, 3, 7)); // seg count, first seg
        w.Lump("NODES", Shorts( // x, y, dx, dy, right bbox (top, bottom, left, right), left bbox, right child, left child
            128, 0, 256, 0, 0, -128, 128, 384, 128, 0, 128, 384, unchecked((short)0x8001), unchecked((short)0x8002),
            128, -128, 0, 256, 128, -128, 128, 384, 128, -128, -128, 128, 0, unchecked((short)0x8000)));
        w.Lump("SECTORS", Concat(
            Sector(0, 128, "FLOOR1", "FLOOR2", 160),
            Sector(16, 112, "LAVA1", "FLOOR1", 208)));
        w.Lump("REJECT", new byte[1]); // 2 × 2 bits, all clear: every sector sees every other
        w.Lump("BLOCKMAP", BuildBlockmap(-136, -136, 5, 3));
    }

    private static byte[] Sidedef(string upper, string lower, string middle, short sector, short xOffset = 0, short yOffset = 0)
    {
        byte[] side = new byte[30];
        BinaryPrimitives.WriteInt16LittleEndian(side, xOffset);
        BinaryPrimitives.WriteInt16LittleEndian(side.AsSpan(2), yOffset);
        Encoding.ASCII.GetBytes(upper, side.AsSpan(4));
        Encoding.ASCII.GetBytes(lower, side.AsSpan(12));
        Encoding.ASCII.GetBytes(middle, side.AsSpan(20));
        BinaryPrimitives.WriteInt16LittleEndian(side.AsSpan(28), sector);
        return side;
    }

    private static byte[] Sector(short floor, short ceiling, string floorFlat, string ceilingFlat, short light)
    {
        byte[] sector = new byte[26]; // floor, ceiling, floor flat, ceiling flat, light, special, tag
        BinaryPrimitives.WriteInt16LittleEndian(sector, floor);
        BinaryPrimitives.WriteInt16LittleEndian(sector.AsSpan(2), ceiling);
        Encoding.ASCII.GetBytes(floorFlat, sector.AsSpan(4));
        Encoding.ASCII.GetBytes(ceilingFlat, sector.AsSpan(12));
        BinaryPrimitives.WriteInt16LittleEndian(sector.AsSpan(20), light);
        return sector;
    }

    /// <summary>
    /// A blockmap of <paramref name="width"/> × <paramref name="height"/> blocks
    /// of 128 from the origin: each block lists (after the customary 0) the
    /// linedefs whose bounding box touches it, which is exact for these
    /// axis-aligned lines.
    /// </summary>
    private static byte[] BuildBlockmap(short originX, short originY, short width, short height)
    {
        var offsets = new List<short> { originX, originY, width, height };
        var lists = new List<short>();
        int listStart = 4 + width * height;
        for (int by = 0; by < height; by++)
        {
            for (int bx = 0; bx < width; bx++)
            {
                offsets.Add((short)(listStart + lists.Count));
                int left = originX + bx * 128, bottom = originY + by * 128;
                lists.Add(0);
                for (int i = 0; i < MapLinedefs.GetLength(0); i++)
                {
                    short v1 = MapLinedefs[i, 0], v2 = MapLinedefs[i, 1];
                    int x1 = MapVertexes[2 * v1], y1 = MapVertexes[2 * v1 + 1], x2 = MapVertexes[2 * v2], y2 = MapVertexes[2 * v2 + 1];
                    if (Math.Max(x1, x2) >= left && Math.Min(x1, x2) <= left + 128 && Math.Max(y1, y2) >= bottom && Math.Min(y1, y2) <= bottom + 128)
                        lists.Add((short)i);
                }
                lists.Add(-1);
            }
        }
        offsets.AddRange(lists);
        return Shorts(offsets.ToArray());
    }

    private static byte[] Concat(params byte[][] parts)
    {
        var all = new List<byte>();
        foreach (byte[] part in parts)
            all.AddRange(part);
        return all.ToArray();
    }

    private static byte[] Shorts(params short[] values)
    {
        byte[] data = new byte[values.Length * 2];
        for (int i = 0; i < values.Length; i++)
            BinaryPrimitives.WriteInt16LittleEndian(data.AsSpan(i * 2), values[i]);
        return data;
    }

    // ---- Other lumps ----

    private static byte[] BuildEndoom()
    {
        byte[] lump = new byte[80 * 25 * 2];
        string text = "IsoDoom synthetic test IWAD - generated content, no id Software data";
        for (int i = 0; i < 80 * 25; i++)
        {
            lump[i * 2] = (byte)' ';
            lump[i * 2 + 1] = 0x1F; // white on blue
        }
        int start = 12 * 80 + (80 - text.Length) / 2;
        for (int i = 0; i < text.Length; i++)
            lump[(start + i) * 2] = (byte)text[i];
        return lump;
    }

    private static byte[] BuildDemo()
    {
        // v1.9 header: version, skill, episode, map, deathmatch, respawn, fast, nomonsters, consoleplayer, playeringame[4].
        var demo = new List<byte> { 109, 2, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0 };
        for (int tic = 0; tic < 35; tic++)
            demo.AddRange(new byte[] { 25, 0, (byte)(tic < 17 ? 2 : 0), 0 }); // forwardmove, sidemove, angleturn, buttons
        demo.Add(0x80); // DEMOMARKER
        return demo.ToArray();
    }

    private static byte[] BuildGenmidi()
    {
        // "#OPL_II#", 175 instruments of 36 bytes, 175 names of 32 bytes (all instruments silent).
        byte[] lump = new byte[8 + 175 * 36 + 175 * 32];
        Encoding.ASCII.GetBytes("#OPL_II#", lump);
        for (int i = 0; i < 175; i++)
            Encoding.ASCII.GetBytes($"Synthetic {i}", lump.AsSpan(8 + 175 * 36 + i * 32));
        return lump;
    }

    private static byte[] BuildMus()
    {
        // MUS: header, then two notes on channel 0 and the score end (event byte: last-in-group flag, type, channel).
        byte[] score =
        {
            0x90, 0x80 | 60, 100, 16, // play note 60 at volume 100; delay 16 tics
            0x80, 60, 16,             // release note 60; delay 16
            0x90, 64, 16,             // play note 64 (same volume); delay 16
            0x00, 64,                 // release note 64
            0x60,                     // score end
        };
        byte[] lump = new byte[16 + score.Length];
        Encoding.ASCII.GetBytes("MUS\x1A", lump);
        BinaryPrimitives.WriteUInt16LittleEndian(lump.AsSpan(4), (ushort)score.Length);
        BinaryPrimitives.WriteUInt16LittleEndian(lump.AsSpan(6), 16);
        BinaryPrimitives.WriteUInt16LittleEndian(lump.AsSpan(8), 1); // primary channels
        score.CopyTo(lump, 16);
        return lump;
    }

    private static byte[] BuildMidi()
    {
        byte[] track = { 0x00, 0x90, 60, 100, 0x60, 0x80, 60, 0, 0x00, 0xFF, 0x2F, 0x00 }; // note on, note off, end of track
        var midi = new List<byte>();
        midi.AddRange(Encoding.ASCII.GetBytes("MThd"));
        midi.AddRange(new byte[] { 0, 0, 0, 6, 0, 0, 0, 1, 0, 96 }); // format 0, 1 track, 96 ticks per quarter
        midi.AddRange(Encoding.ASCII.GetBytes("MTrk"));
        midi.AddRange(new byte[] { 0, 0, 0, (byte)track.Length });
        midi.AddRange(track);
        return midi.ToArray();
    }

    private static byte[] BuildDmxSound()
    {
        // DMX: format 3, 11025 Hz, sample count (incl. the 16 pad bytes either side), then 8-bit unsigned samples.
        const int samples = 2048;
        byte[] lump = new byte[8 + 16 + samples + 16];
        BinaryPrimitives.WriteUInt16LittleEndian(lump, 3);
        BinaryPrimitives.WriteUInt16LittleEndian(lump.AsSpan(2), 11025);
        BinaryPrimitives.WriteUInt32LittleEndian(lump.AsSpan(4), samples + 32);
        for (int i = 0; i < 16; i++)
        {
            lump[8 + i] = 128;
            lump[8 + 16 + samples + i] = 128;
        }
        for (int i = 0; i < samples; i++)
        {
            int amplitude = 100 * (samples - i) / samples;
            lump[8 + 16 + i] = (byte)(128 + ((i / 12) % 2 == 0 ? amplitude : -amplitude)); // decaying square wave
        }
        return lump;
    }

    private static byte[] BuildPcSpeakerSound()
    {
        // PC speaker: format 0, tone count, then one tone byte per 1/140 s.
        byte[] lump = new byte[4 + 20];
        BinaryPrimitives.WriteUInt16LittleEndian(lump.AsSpan(2), 20);
        for (int i = 0; i < 20; i++)
            lump[4 + i] = (byte)(60 - i * 2);
        return lump;
    }

    // ---- WAD writer ----

    private sealed class Writer
    {
        private readonly List<(string Name, byte[] Data)> _lumps = new();

        public void Lump(string name, byte[]? data = null) => _lumps.Add((name, data ?? Array.Empty<byte>()));

        public void Markers(params string[] names)
        {
            foreach (string name in names)
                Lump(name);
        }

        /// <summary>Header, lump data, then the directory (as id's tools lay it out).</summary>
        public byte[] Build()
        {
            int dataSize = 0;
            foreach ((_, byte[] data) in _lumps)
                dataSize += data.Length;
            byte[] wad = new byte[12 + dataSize + 16 * _lumps.Count];
            Encoding.ASCII.GetBytes("IWAD", wad);
            BinaryPrimitives.WriteInt32LittleEndian(wad.AsSpan(4), _lumps.Count);
            BinaryPrimitives.WriteInt32LittleEndian(wad.AsSpan(8), 12 + dataSize);
            int pos = 12;
            for (int i = 0; i < _lumps.Count; i++)
            {
                (string name, byte[] data) = _lumps[i];
                if (name.Length > 8)
                    throw new InvalidOperationException($"Lump name {name} is longer than 8 characters.");
                data.CopyTo(wad, pos);
                Span<byte> entry = wad.AsSpan(12 + dataSize + 16 * i, 16);
                BinaryPrimitives.WriteInt32LittleEndian(entry, data.Length == 0 ? 0 : pos);
                BinaryPrimitives.WriteInt32LittleEndian(entry[4..], data.Length);
                Encoding.ASCII.GetBytes(name, entry[8..]);
                pos += data.Length;
            }
            return wad;
        }
    }
}
