using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.Text;
using IsoDoom.Map;
using IsoDoom.Wad;
using IsoDoom.Wad.Graphics;

namespace IsoDoom.Tools.SyntheticIwad;

/// <summary>
/// A small synthetic IWAD for running the WAD viewer check in CI (T1.6b),
/// where no id Software WAD is available. Everything in it is generated here
/// (procedural palettes, patterns and shapes), so it holds no id data and can
/// be built anywhere; the output is deterministic.
/// <para>
/// It identifies as shareware Doom (<c>E1M1</c>, no <c>E3M1</c>) and has at
/// least one lump of every <see cref="LumpKind"/>: <c>PLAYPAL</c> (14
/// palettes) and <c>COLORMAP</c> (34 maps); <c>PNAMES</c>, <c>TEXTURE1</c> and
/// <c>TEXTURE2</c> with a single-patch, a multi-patch (overlapping, clipped
/// at the edges), a masked and a non-128-high texture; wall patches in
/// <c>P_START</c>/<c>P1_START</c> with a duplicate name (the later copy wins,
/// the earlier one is overridden); flats in <c>F_START</c>/<c>F1_START</c>;
/// sprites in <c>S_START</c> with a fully rotated frame (mirrored pairs) and
/// rotation-0 frames (one full bright in its spawn state, one for a thing
/// hanging from the ceiling), plus a sprite lump no sprite uses; global graphics
/// (title, status bar, menu, font glyphs, with offsets and transparency); a
/// map with a real BSP tree and every wall-section case (see <c>BuildMap</c>), and
/// <c>E1M2</c>, the specials map M5's tasks add their cases to (see
/// <c>BuildSpecialsMap</c>; a switch texture pair); ENDOOM, GENMIDI, DMXGUS, MUS and MIDI music, DMX and PC
/// speaker sounds, a demo and a plain text lump.
/// </para>
/// </summary>
public static class SyntheticIwad
{
    public const string DefaultFileName = "isodoom-synthetic.wad";

    /// <summary>The IWAD's bytes.</summary>
    public static byte[] Build()
    {
        var w = new Writer();
        w.Lump("PLAYPAL", BuildPlaypal());
        w.Lump("COLORMAP", BuildColormap());
        w.Lump("ENDOOM", BuildEndoom());
        w.Lump("DEMO1", BuildDemo());
        BuildMap(w);
        BuildSpecialsMap(w);
        w.Lump("TEXTURE1", BuildTextureLump(
            new Tex("NULLTEX", 64, 64, false, (0, 0, 0)), // texture 0 is never drawn (vanilla's AASTINKY/AASHITTY)
            new Tex("BRICK1", 64, 64, false, (0, 0, 0)),
            new Tex("BRKPNL", 128, 128, false, (0, 0, 0), (64, 0, 1), (-32, 64, 0), (32, 64, 0), (96, 64, 0)),
            new Tex("GRATE", 64, 64, true, (0, 0, 2), (32, 0, 2)),
            new Tex("PANEL", 64, 72, false, (0, -8, 1))));
        w.Lump("TEXTURE2", BuildTextureLump(
            new Tex("WINFRAME", 32, 64, false, (0, 0, 2)),
            new Tex("SW1BRCOM", 64, 128, false, (0, 0, 3)), // a switch pair of p_switch.c's list (T5.1, E1M2)
            new Tex("SW2BRCOM", 64, 128, false, (0, 0, 4))));
        w.Lump("PNAMES", BuildPNames("WALLBRK", "WALLPNL", "WINDOW", "SWOFF", "SWON"));
        w.Lump("GENMIDI", BuildGenmidi());
        w.Lump("DMXGUS", Encoding.ASCII.GetBytes("# Synthetic test patch map\r\n0, 2, 1, 0, acpiano\r\n"));
        w.Lump("D_E1M1", BuildMus());
        w.Lump("D_INTRO", BuildMidi());
        w.Lump("DSPISTOL", BuildDmxSound());
        w.Lump("DPPISTOL", BuildPcSpeakerSound());
        w.Lump("README", Encoding.ASCII.GetBytes(
            "IsoDoom synthetic test IWAD. Generated by tools/SyntheticIwad for the WAD viewer check in CI.\n"
            + "All content is procedural; it contains no id Software data. Not a playable game.\n"));

        // Global graphics (found by structure, as the UI lumps are).
        w.Lump("TITLEPIC", EncodePatch(TitlePic()));
        w.Lump("STBAR", EncodePatch(StatusBar()));
        w.Lump("M_DOOM", EncodePatch(MenuLogo()));
        w.Lump("STCFN065", EncodePatch(Glyph(GlyphA)));
        w.Lump("STCFN066", EncodePatch(Glyph(GlyphB)));
        w.Lump("STCFN067", EncodePatch(Glyph(GlyphC)));

        w.Markers("S_START");
        Image troo = Arrow();
        w.Lump("TROOA1", EncodePatch(troo));
        w.Lump("TROOA2A8", EncodePatch(troo.Tinted(1)));
        w.Lump("TROOA3A7", EncodePatch(troo.Tinted(2)));
        w.Lump("TROOA4A6", EncodePatch(troo.Tinted(3)));
        w.Lump("TROOA5", EncodePatch(troo.Tinted(4)));
        w.Lump("BAR1A0", EncodePatch(Barrel(0)));
        w.Lump("BAR1B0", EncodePatch(Barrel(1)));
        w.Lump("XXXXA0", EncodePatch(Barrel(2))); // in no sprite name list: listed, but no sprite frame
        w.Lump("COLUA0", EncodePatch(Lamp()));      // floor lamp (MT_MISC31): a full-bright spawn frame
        w.Lump("GOR2A0", EncodePatch(Hanging()));   // hanging body (MT_MISC56): spawns on the ceiling
        w.Markers("S_END");

        w.Markers("P_START", "P1_START");
        w.Lump("WALLBRK", EncodePatch(Bricks()));
        w.Lump("WALLPNL", EncodePatch(Panel(0)));
        w.Lump("WINDOW", EncodePatch(Window()));
        w.Lump("WALLPNL", EncodePatch(Panel(2))); // duplicate: this one wins, the first is overridden
        w.Lump("SWOFF", EncodePatch(Switch(false)));
        w.Lump("SWON", EncodePatch(Switch(true)));
        w.Markers("P1_END", "P_END");

        w.Markers("F_START", "F1_START");
        w.Lump("FLOOR1", Checker().Pixels);
        w.Lump("FLOOR2", Diagonal().Pixels);
        w.Lump("LAVA1", Waves().Pixels);
        w.Lump("F_SKY1", Solid(64, 64, (x, y) => Index(1, 2, 3)).Pixels); // the sky flat (r_sky.h SKYFLATNAME)
        w.Markers("F1_END", "F_END");
        return w.Build();
    }

    /// <summary>
    /// Checks that the IWAD loads as the viewer loads it and has what the viewer
    /// check is meant to exercise. Returns the problems found (empty when fine).
    /// </summary>
    public static List<string> Check(WadArchive wad)
    {
        var problems = new List<string>();
        IwadInfo info = IwadIdentification.D_IdentifyVersion(wad);
        if (info.GameMode != GameMode.shareware)
            problems.Add($"identifies as {info.GameMode}, expected shareware");
        GraphicsCatalog catalog = GraphicsCatalog.Load(wad);
        foreach (GraphicCategory c in Enum.GetValues<GraphicCategory>())
        {
            if (catalog.Count(c) == 0)
                problems.Add($"no {c} in the graphics catalog");
        }
        var kinds = new HashSet<LumpKind>();
        bool overridden = false;
        foreach (LumpEntry e in LumpDirectory.Build(wad))
        {
            kinds.Add(e.Kind);
            overridden |= e.IsOverridden;
        }
        foreach (LumpKind k in Enum.GetValues<LumpKind>())
        {
            if (!kinds.Contains(k))
                problems.Add($"no lump of kind {LumpDirectory.KindName(k)}");
        }
        if (!overridden)
            problems.Add("no overridden lump");
        try
        {
            Level map = Level.Load(wad, "E1M1");
            if (map.Nodes.Length < 2 || map.Sectors.Length < 2)
                problems.Add($"E1M1 has {map.Nodes.Length} nodes and {map.Sectors.Length} sectors, expected a BSP tree over several sectors");
            WallSections walls = WallSections.Build(map, catalog.Textures);
            if (walls.Missing.Count > 0)
                problems.Add($"E1M1 has missing wall textures: {string.Join(", ", walls.Missing)}");
            foreach (WallSectionKind k in Enum.GetValues<WallSectionKind>())
            {
                if (!Has(walls, s => s.Kind == k && s.Texture != 0))
                    problems.Add($"E1M1 has no textured {k} wall section");
            }
            if (!Has(walls, s => s.Kind == WallSectionKind.Upper && (s.Line.Flags & Line.ML_DONTPEGTOP) != 0 && s.Texture != 0))
                problems.Add("E1M1 has no upper unpegged wall");
            if (!Has(walls, s => s.Kind == WallSectionKind.Lower && (s.Line.Flags & Line.ML_DONTPEGBOTTOM) != 0 && s.Texture != 0))
                problems.Add("E1M1 has no lower unpegged wall");
            if (!Has(walls, s => s.BackSector is { CeilingPic: WallSections.SKYFLATNAME } && s.FrontSector.CeilingPic == WallSections.SKYFLATNAME))
                problems.Add("E1M1 has no line with a sky ceiling on both sides");
            if (!Has(walls, s => s.BackSector is { } b && b.FloorHeight == b.CeilingHeight))
                problems.Add("E1M1 has no closed door (a two-sided line onto a sector with no height)");
        }
        catch (WadFormatException e)
        {
            problems.Add($"E1M1 does not load: {e.Message}");
        }
        try
        {
            Level specials = Level.Load(wad, "E1M2");
            if (specials.Sectors.Length != 1 + SpecialsAlcoves || specials.Sectors[0].Lines.Count != 3 + SpecialsAlcoves)
                problems.Add($"E1M2 has {specials.Sectors.Length} sectors, its corridor {specials.Sectors[0].Lines.Count} lines; expected {1 + SpecialsAlcoves} and {3 + SpecialsAlcoves}");
            WallSections walls = WallSections.Build(specials, catalog.Textures);
            if (walls.Missing.Count > 0)
                problems.Add($"E1M2 has missing wall textures: {string.Join(", ", walls.Missing)}");
            if (!Has(walls, s => s.Texture != 0 && catalog.Textures.TextureDefs[s.Texture].Name == "SW1BRCOM"))
                problems.Add("E1M2 has no switch texture");
        }
        catch (WadFormatException e)
        {
            problems.Add($"E1M2 does not load: {e.Message}");
        }
        return problems;
    }

    private static bool Has(WallSections walls, Func<WallSection, bool> match)
    {
        foreach (WallSection s in walls.Sections)
        {
            if (match(s))
                return true;
        }
        return false;
    }

    // ---- Palette ----
    // Palette 0 is a 8x8x4 RGB grid: index = r | g << 3 | b << 6 (r, g in 0..7, b in 0..3).
    // No component reaches 255, which leaves the viewer check's background colours free.

    private static int Index(int r, int g, int b) => r | g << 3 | b << 6;

    private static (int R, int G, int B) BaseColor(int i) => ((i & 7) * 36, ((i >> 3) & 7) * 36, (i >> 6) * 84);

    private static byte[] BuildPlaypal()
    {
        // 0: normal; 1-8: red (damage, berserk); 9-12: gold (pickup); 13: green (radiation suit), as st_stuff.c numbers them.
        var tints = new List<(int R, int G, int B, int Num, int Den)> { (0, 0, 0, 0, 1) };
        for (int k = 1; k <= 8; k++)
            tints.Add((255, 0, 0, k, 9));
        for (int k = 1; k <= 4; k++)
            tints.Add((215, 186, 69, k, 8));
        tints.Add((0, 255, 0, 1, 8));

        byte[] lump = new byte[Playpal.PaletteSize * tints.Count];
        for (int p = 0; p < tints.Count; p++)
        {
            (int tr, int tg, int tb, int num, int den) = tints[p];
            for (int i = 0; i < 256; i++)
            {
                (int r, int g, int b) = BaseColor(i);
                int o = p * Playpal.PaletteSize + i * 3;
                lump[o] = (byte)(r + (tr - r) * num / den);
                lump[o + 1] = (byte)(g + (tg - g) * num / den);
                lump[o + 2] = (byte)(b + (tb - b) * num / den);
            }
        }
        return lump;
    }

    private static byte[] BuildColormap()
    {
        // 0-31: darker in 32 steps; 32: inverted greyscale (invulnerability); 33: all black.
        byte[] lump = new byte[Colormap.MapSize * 34];
        for (int m = 0; m < 32; m++)
        {
            for (int i = 0; i < 256; i++)
            {
                int r = i & 7, g = (i >> 3) & 7, b = i >> 6;
                lump[m * 256 + i] = (byte)Index((r * (32 - m) + 16) / 32, (g * (32 - m) + 16) / 32, (b * (32 - m) + 16) / 32);
            }
        }
        for (int i = 0; i < 256; i++)
        {
            (int r, int g, int b) = BaseColor(i);
            int inv = 255 - (r * 3 + g * 6 + b) / 10; // 0..255
            lump[32 * 256 + i] = (byte)Index((inv * 7 + 127) / 255, (inv * 7 + 127) / 255, (inv * 3 + 127) / 255);
        }
        return lump;
    }

    // ---- Images ----

    private sealed class Image
    {
        public readonly int Width, Height, Left, Top;
        public readonly byte[] Pixels;
        public readonly bool[] Opaque;

        public Image(int width, int height, int left = 0, int top = 0)
        {
            Width = width;
            Height = height;
            Left = left;
            Top = top;
            Pixels = new byte[width * height];
            Opaque = new bool[width * height];
        }

        public void Set(int x, int y, int index)
        {
            Pixels[y * Width + x] = (byte)index;
            Opaque[y * Width + x] = true;
        }

        /// <summary>A copy with the blue level shifted by <paramref name="step"/> (wrapping), so each rotation looks different.</summary>
        public Image Tinted(int step)
        {
            var copy = new Image(Width, Height, Left, Top);
            for (int p = 0; p < Pixels.Length; p++)
            {
                if (Opaque[p])
                    copy.Set(p % Width, p / Width, (Pixels[p] & 63) | ((((Pixels[p] >> 6) + step) & 3) << 6));
            }
            return copy;
        }
    }

    private static Image Solid(int width, int height, Func<int, int, int> color, int left = 0, int top = 0)
    {
        var img = new Image(width, height, left, top);
        for (int y = 0; y < height; y++)
        {
            for (int x = 0; x < width; x++)
                img.Set(x, y, color(x, y));
        }
        return img;
    }

    private static Image Bricks() => Solid(64, 64, (x, y) =>
    {
        int row = y / 16, bx = (x + (row % 2) * 16) % 32;
        if (y % 16 == 15 || bx == 31)
            return Index(4, 4, 1); // mortar
        return Index(5 + (row + bx / 8) % 3, 1 + (y % 16) / 6, 0);
    });

    private static Image Panel(int hue) => Solid(64, 128, (x, y) =>
    {
        int edge = Math.Min(Math.Min(x, 63 - x), Math.Min(y % 64, 63 - y % 64));
        int level = edge < 2 ? 7 : edge < 4 ? 2 : 3 + (y % 64) / 22;
        return Index(level, level, hue + (edge < 2 ? 1 : 0));
    });

    /// <summary>A switch: a panel with a plate in the middle, lit when <paramref name="on"/>.</summary>
    private static Image Switch(bool on) => Solid(64, 128, (x, y) =>
    {
        bool plate = x >= 20 && x < 44 && y >= 48 && y < 80;
        if (plate)
            return on ? Index(7, 6, 0) : Index(2, 1, 0);
        return Index(3 + (x / 16 + y / 32) % 2, 3, 1);
    });

    private static Image Window()
    {
        var img = new Image(32, 64);
        for (int y = 0; y < 64; y++)
        {
            for (int x = 0; x < 32; x++)
            {
                bool frame = x < 4 || x >= 28 || y < 4 || y >= 60 || (x >= 15 && x <= 16) || (y >= 30 && y <= 33);
                if (frame)
                    img.Set(x, y, Index(1 + x % 3, 3, 2));
            }
        }
        return img;
    }

    private static Image Checker() => Solid(64, 64, (x, y) => ((x / 8 + y / 8) % 2 == 0) ? Index(6, 6, 2) : Index(2, 2, 1));

    private static Image Diagonal() => Solid(64, 64, (x, y) => Index((x + y) / 16, 7 - (x + y) / 18, (x / 16) % 4));

    private static Image Waves() => Solid(64, 64, (x, y) =>
    {
        int t = (x * 3 + Tri(y * 4)) % 64;
        return Index(7, t / 10, 0);
    });

    private static int Tri(int v) => Math.Abs(v % 64 - 32); // a triangle wave in integers

    private static Image TitlePic() => Solid(320, 200, (x, y) =>
    {
        // An isometric diamond grid over a vertical gradient.
        bool line = (x + 2 * y) % 32 < 2 || (x - 2 * y + 400) % 32 < 2;
        return line ? Index(7, 6, 1) : Index(y / 40, y / 50, 3 - y / 67);
    });

    private static Image StatusBar() => Solid(320, 32, (x, y) =>
    {
        bool box = x % 64 < 2 || y < 2 || y >= 30;
        return box ? Index(6, 6, 1) : Index(3, 3, 1 + (x / 64) % 2);
    });

    private static Image MenuLogo()
    {
        // A diamond outline with a transparent inside and outside, offsets as menu graphics have.
        var img = new Image(96, 40, -4, -2);
        for (int y = 0; y < 40; y++)
        {
            for (int x = 0; x < 96; x++)
            {
                int d = Math.Abs(x - 48) * 40 / 96 + Math.Abs(y - 20);
                if (d >= 14 && d <= 20)
                    img.Set(x, y, Index(7, d - 13, 0));
            }
        }
        return img;
    }

    private static readonly string[] GlyphA = { "..#..", ".#.#.", "#...#", "#####", "#...#", "#...#", "#...#" };
    private static readonly string[] GlyphB = { "####.", "#...#", "####.", "#...#", "#...#", "#...#", "####." };
    private static readonly string[] GlyphC = { ".###.", "#...#", "#....", "#....", "#....", "#...#", ".###." };

    private static Image Glyph(string[] rows)
    {
        var img = new Image(rows[0].Length, rows.Length);
        for (int y = 0; y < rows.Length; y++)
        {
            for (int x = 0; x < rows[y].Length; x++)
            {
                if (rows[y][x] == '#')
                    img.Set(x, y, Index(7, 7 - y / 2, 0));
            }
        }
        return img;
    }

    private static Image Arrow()
    {
        // Asymmetric (points right, notch at the top), so a mirrored rotation is visibly mirrored. A foot
        // (rows 44-55) reaches 4 rows below the origin, as many of id's sprites do (T3.5).
        var img = new Image(41, 56, 20, 52);
        for (int y = 0; y < 56; y++)
        {
            for (int x = 0; x < 41; x++)
            {
                bool head = x >= 20 && Math.Abs(y - 28) <= 40 - x;
                bool shaft = x < 20 && y >= 22 && y <= 34;
                bool notch = y < 6 && x > 26;
                bool foot = y >= 44 && x >= 12 && x <= 24 + (y - 44) / 3;
                if ((head || shaft || foot) && !notch)
                    img.Set(x, y, Index(x / 6, 2 + y / 14, 1));
            }
        }
        return img;
    }

    private static Image Lamp()
    {
        // A post with a bright bulb; 3 rows below the origin.
        var img = new Image(15, 48, 7, 45);
        for (int y = 0; y < 48; y++)
        {
            for (int x = 0; x < 15; x++)
            {
                bool bulb = y < 12 && (x - 7) * (x - 7) + (y - 6) * (y - 6) <= 36;
                bool post = y >= 12 && Math.Abs(x - 7) <= (y >= 44 ? 6 : 2);
                if (bulb || post)
                    img.Set(x, y, bulb ? Index(7, 6 + (x + y) % 2, 1) : Index(2 + y % 3, 2, 2));
            }
        }
        return img;
    }

    private static Image Hanging()
    {
        // A rope and a hanging shape, asymmetric; its origin is near the bottom, as id's hanging sprites.
        var img = new Image(20, 60, 9, 58);
        for (int y = 0; y < 60; y++)
        {
            for (int x = 0; x < 20; x++)
            {
                bool rope = y < 20 && x >= 8 && x <= 10;
                bool body = y >= 20 && Math.Abs(x - 9) <= 3 + (y - 20) / 8 && !(y > 50 && x < 6);
                if (rope || body)
                    img.Set(x, y, rope ? Index(5, 5, 0) : Index(6, (x + 2 * y) % 4, 0));
            }
        }
        return img;
    }

    private static Image Barrel(int frame)
    {
        var img = new Image(23, 32, 11, 30);
        for (int y = 0; y < 32; y++)
        {
            for (int x = 0; x < 23; x++)
            {
                bool rim = y < 3 || y >= 29;
                bool body = Math.Abs(x - 11) <= (rim ? 9 : 11);
                if (body)
                    img.Set(x, y, rim ? Index(4, 4, 2) : Index(1 + frame, 3 + (x + frame * 3) % 5, 0));
            }
        }
        return img;
    }

    /// <summary>Encodes a patch: header, column offsets, then each column's posts (opaque runs of up to 128 pixels).</summary>
    private static byte[] EncodePatch(Image img)
    {
        if (img.Height > 254)
            throw new ArgumentException("Tall patches need relative topdeltas; not generated here.");
        var body = new List<byte>();
        int dataStart = 8 + 4 * img.Width;
        int[] offsets = new int[img.Width];
        for (int x = 0; x < img.Width; x++)
        {
            offsets[x] = dataStart + body.Count;
            int y = 0;
            while (y < img.Height)
            {
                if (!img.Opaque[y * img.Width + x])
                {
                    y++;
                    continue;
                }
                int start = y;
                while (y < img.Height && y - start < 128 && img.Opaque[y * img.Width + x])
                    y++;
                body.Add((byte)start);
                body.Add((byte)(y - start));
                body.Add(0); // unused pad byte
                for (int p = start; p < y; p++)
                    body.Add(img.Pixels[p * img.Width + x]);
                body.Add(0); // unused pad byte
            }
            body.Add(0xFF);
        }
        byte[] lump = new byte[dataStart + body.Count];
        BinaryPrimitives.WriteInt16LittleEndian(lump, (short)img.Width);
        BinaryPrimitives.WriteInt16LittleEndian(lump.AsSpan(2), (short)img.Height);
        BinaryPrimitives.WriteInt16LittleEndian(lump.AsSpan(4), (short)img.Left);
        BinaryPrimitives.WriteInt16LittleEndian(lump.AsSpan(6), (short)img.Top);
        for (int x = 0; x < img.Width; x++)
            BinaryPrimitives.WriteInt32LittleEndian(lump.AsSpan(8 + 4 * x), offsets[x]);
        body.CopyTo(lump, dataStart);
        return lump;
    }

    // ---- Wall textures (r_data.c maptexture_t / mappatch_t) ----

    private sealed record Tex(string Name, int Width, int Height, bool Masked, params (int X, int Y, int Patch)[] Patches);

    private static byte[] BuildPNames(params string[] names)
    {
        byte[] lump = new byte[4 + 8 * names.Length];
        BinaryPrimitives.WriteInt32LittleEndian(lump, names.Length);
        for (int i = 0; i < names.Length; i++)
            Encoding.ASCII.GetBytes(names[i], lump.AsSpan(4 + 8 * i));
        return lump;
    }

    private static byte[] BuildTextureLump(params Tex[] textures)
    {
        var body = new List<byte>();
        int dirSize = 4 + 4 * textures.Length;
        byte[] dir = new byte[dirSize];
        BinaryPrimitives.WriteInt32LittleEndian(dir, textures.Length);
        for (int i = 0; i < textures.Length; i++)
        {
            Tex t = textures[i];
            BinaryPrimitives.WriteInt32LittleEndian(dir.AsSpan(4 + 4 * i), dirSize + body.Count);
            byte[] mt = new byte[22 + 10 * t.Patches.Length];
            Encoding.ASCII.GetBytes(t.Name, mt);
            BinaryPrimitives.WriteInt32LittleEndian(mt.AsSpan(8), t.Masked ? 1 : 0);
            BinaryPrimitives.WriteInt16LittleEndian(mt.AsSpan(12), (short)t.Width);
            BinaryPrimitives.WriteInt16LittleEndian(mt.AsSpan(14), (short)t.Height);
            BinaryPrimitives.WriteInt16LittleEndian(mt.AsSpan(20), (short)t.Patches.Length);
            for (int j = 0; j < t.Patches.Length; j++)
            {
                Span<byte> mp = mt.AsSpan(22 + 10 * j);
                BinaryPrimitives.WriteInt16LittleEndian(mp, (short)t.Patches[j].X);
                BinaryPrimitives.WriteInt16LittleEndian(mp[2..], (short)t.Patches[j].Y);
                BinaryPrimitives.WriteInt16LittleEndian(mp[4..], (short)t.Patches[j].Patch);
                BinaryPrimitives.WriteInt16LittleEndian(mp[6..], 1); // stepdir (unused)
            }
            body.AddRange(mt);
        }
        byte[] lump = new byte[dirSize + body.Count];
        dir.CopyTo(lump, 0);
        body.CopyTo(lump, dirSize);
        return lump;
    }

    // ---- Map: two rooms, three subsectors under two BSP nodes, and a wall-section test strip ----
    //
    //  (-128,128) v0 ---L0--- v1 (128,128) ---L4--- v4 (384,128)
    //       |                  |                       |
    //       L3   west room     L1   east room, north   L5      y = 0: partition of
    //       |    sector 0      |    subsector 2        |       node 0 (no linedef),
    //       |    subsector 0   v7 - - - - - - - - - -  v6      split vertices v6, v7
    //       |                  |    east room, south   |
    //       |                  |    subsector 1        |
    // (-128,-128) v3 ---L2--- v2 (128,-128) ---L6--- v5 (384,-128)
    //
    // L1 is two-sided (the east room is raised 16 and its ceiling 16 lower, so
    // the west side has upper and lower textures; the east side has a masked
    // GRATE). Node 1 splits along L1, node 0 splits the east room at y = 0, so
    // the east subsectors each have an edge with no seg on it, as real node
    // builders make them. Linedefs run clockwise around each room, so their
    // right (front) sides face in.
    //
    // East of x = 448 (the root node's partition, no linedef), a separate strip
    // covers the other wall-section cases (T2.3), one sector per subsector:
    //
    //  v8 --L7-- v9 -L11- v10 -----L14----- v11 --L17-- v12      y = 128
    //  |         |   D    |                 |           |
    //  L10  C    L8 door  L12   A courtyard L15  B ledge L18
    //  |         |        |     (sky)       |   (sky)   |
    //  v13 -L9-- v14 -L13- v15 ----L16----- v16 --L19-- v17      y = -128
    //  x = 512   640      656               912         1040
    //
    // C (sector 2): a room, floor 0, ceiling 128; its west wall is lower
    // unpegged with a y offset. D (sector 3): a closed door (floor = ceiling =
    // 0), so L8 gives C a pegged upper and L12 gives A an upper and lower
    // unpegged pair. A (sector 4) and B (sector 5) have F_SKY1 ceilings at
    // 256 and 192, so L15 has no upper on A's side (the sky rule) although
    // its texture is "-"; L15 has a lower (unpegged, so anchored at the back
    // ceiling by the sky rule) and a masked GRATE (unpegged) on both sides.
    // B's floor (64) is 80 above A's, more than the cutaway's cutoff (32), so
    // a centre in A just west of L15 has B's floor cut and capped (T3.4a).
    private static readonly short[] MapVertexes =
    {
        -128, 128, 128, 128, 128, -128, -128, -128, // v0-v3: west room
        384, 128, 384, -128,                        // v4, v5: east room
        384, 0, 128, 0,                             // v6, v7: where node 0's partition splits L5 and L1
        512, 128, 640, 128, 656, 128, 912, 128, 1040, 128,      // v8-v12: the strip's north edge
        512, -128, 640, -128, 656, -128, 912, -128, 1040, -128, // v13-v17: its south edge
    };

    private const short TwoSided = Line.ML_TWOSIDED, PegTop = Line.ML_DONTPEGTOP, PegBottom = Line.ML_DONTPEGBOTTOM;

    // v1, v2, flags, special, tag, right side, left side (-1: none)
    private static readonly short[,] MapLinedefs =
    {
        { 0, 1, 1, 0, 0, 0, -1 }, // L0: west room north
        { 1, 2, 4, 0, 0, 1, 2 },  // L1: two-sided, west room in front, east room behind
        { 2, 3, 1, 0, 0, 3, -1 }, // L2: west room south
        { 3, 0, 1, 0, 0, 4, -1 }, // L3: west room west
        { 1, 4, 1, 0, 0, 5, -1 }, // L4: east room north
        { 4, 5, 1, 0, 0, 6, -1 }, // L5: east room east
        { 5, 2, 1, 0, 0, 7, -1 }, // L6: east room south
        { 8, 9, 1, 0, 0, 8, -1 },                              // L7: C north
        { 9, 14, TwoSided, 1, 0, 9, 10 },                      // L8: C | door D (a DR door special)
        { 14, 13, 1, 0, 0, 11, -1 },                           // L9: C south
        { 13, 8, 1 | PegBottom, 0, 0, 12, -1 },                // L10: C west, lower unpegged
        { 9, 10, 1 | PegBottom, 0, 0, 13, -1 },                // L11: door track north (no height while closed)
        { 10, 15, TwoSided | PegTop | PegBottom, 0, 0, 14, 15 }, // L12: door D | courtyard A, both unpegged
        { 15, 14, 1 | PegBottom, 0, 0, 16, -1 },               // L13: door track south
        { 10, 11, 1, 0, 0, 17, -1 },                           // L14: A north
        { 11, 16, TwoSided | PegBottom, 0, 0, 18, 19 },        // L15: A | B, sky on both sides, masked GRATE
        { 16, 15, 1, 0, 0, 20, -1 },                           // L16: A south
        { 11, 12, 1, 0, 0, 21, -1 },                           // L17: B north
        { 12, 17, 1, 0, 0, 22, -1 },                           // L18: B east
        { 17, 16, 1, 0, 0, 23, -1 },                           // L19: B south
    };

    private static void BuildMap(Writer w)
    {
        w.Markers("E1M1");
        w.Lump("THINGS", Shorts( // x, y, angle, type, flags (all skills)
            0, 0, 90, 1, 7,           // player 1 start
            64, 64, 0, 2035, 7,       // barrel (BAR1)
            320, 64, 180, 3001, 7,    // imp (TROO), in the east room's north subsector
            // T3.5: imps facing the other seven directions (every rotation and mirror from any one
            // view), a full-bright lamp and a thing hanging from room C's ceiling.
            -80, 80, 0, 3001, 7,
            -80, 0, 45, 3001, 7,
            -80, -80, 90, 3001, 7,
            0, -80, 135, 3001, 7,
            80, -80, 225, 3001, 7,
            80, 0, 270, 3001, 7,
            0, 80, 315, 3001, 7,
            784, 0, 0, 2028, 7,       // floor lamp (COLU, full bright) in courtyard A
            576, 0, 0, 59, 7));       // hanging body (GOR2, MF_SPAWNCEILING) in room C
        var linedefs = new List<short>();
        for (int i = 0; i < MapLinedefs.GetLength(0); i++)
        {
            for (int j = 0; j < MapLinedefs.GetLength(1); j++)
                linedefs.Add(MapLinedefs[i, j]);
        }
        w.Lump("LINEDEFS", Shorts(linedefs.ToArray()));
        w.Lump("SIDEDEFS", Concat(
            Sidedef("-", "-", "BRICK1", 0),         // 0: L0
            Sidedef("PANEL", "PANEL", "-", 0),      // 1: L1 front (west room): upper and lower
            Sidedef("-", "-", "GRATE", 1),          // 2: L1 back (east room): masked, pegged
            Sidedef("-", "-", "BRKPNL", 0, 32),     // 3: L2, with an x offset
            Sidedef("-", "-", "BRICK1", 0),         // 4: L3
            Sidedef("-", "-", "BRKPNL", 1),         // 5: L4
            Sidedef("-", "-", "BRICK1", 1, 0, 8),   // 6: L5, with a y offset
            Sidedef("-", "-", "BRKPNL", 1),         // 7: L6
            Sidedef("-", "-", "BRICK1", 2),         // 8: L7
            Sidedef("PANEL", "-", "-", 2),          // 9: L8 front (C): pegged upper; no lower (same floors)
            Sidedef("-", "-", "-", 3),              // 10: L8 back (door): nothing to draw
            Sidedef("-", "-", "BRICK1", 2),         // 11: L9
            Sidedef("-", "-", "BRICK1", 2, 0, 8),   // 12: L10, lower unpegged with a y offset
            Sidedef("-", "-", "-", 3),              // 13: L11: "-", but no height while the door is closed
            Sidedef("-", "-", "-", 3),              // 14: L12 front (door): nothing to draw
            Sidedef("PANEL", "BRICK1", "-", 4, 16, 4), // 15: L12 back (A): unpegged upper and lower, offsets
            Sidedef("-", "-", "BRICK1", 3),         // 16: L13
            Sidedef("-", "-", "BRKPNL", 4),         // 17: L14
            Sidedef("-", "BRKPNL", "GRATE", 4, 8, 8), // 18: L15 front (A): no upper (sky), lower, masked
            Sidedef("-", "-", "GRATE", 5),          // 19: L15 back (B): masked only
            Sidedef("-", "-", "BRKPNL", 4),         // 20: L16
            Sidedef("-", "-", "BRICK1", 5),         // 21: L17
            Sidedef("-", "-", "BRICK1", 5),         // 22: L18
            Sidedef("-", "-", "BRICK1", 5)));       // 23: L19
        w.Lump("VERTEXES", Shorts(MapVertexes));
        const short East = 0, North = 0x4000, West = unchecked((short)0x8000), South = unchecked((short)0xC000);
        w.Lump("SEGS", Shorts( // v1, v2, angle (BAM >> 16), linedef, side (0 front, 1 back), offset along the linedef side
            0, 1, East, 0, 0, 0,     // seg 0-3: subsector 0, the west room
            1, 2, South, 1, 0, 0,
            2, 3, West, 2, 0, 0,
            3, 0, North, 3, 0, 0,
            6, 5, South, 5, 0, 128,  // seg 4-6: subsector 1, the east room's south half
            5, 2, West, 6, 0, 0,
            2, 7, North, 1, 1, 0,
            7, 1, North, 1, 1, 128,  // seg 7-9: subsector 2, the east room's north half
            1, 4, East, 4, 0, 0,
            4, 6, South, 5, 0, 0,
            8, 9, East, 7, 0, 0,     // seg 10-13: subsector 3, room C
            9, 14, South, 8, 0, 0,
            14, 13, West, 9, 0, 0,
            13, 8, North, 10, 0, 0,
            9, 10, East, 11, 0, 0,   // seg 14-17: subsector 4, door D
            10, 15, South, 12, 0, 0,
            15, 14, West, 13, 0, 0,
            14, 9, North, 8, 1, 0,
            10, 11, East, 14, 0, 0,  // seg 18-21: subsector 5, courtyard A
            11, 16, South, 15, 0, 0,
            16, 15, West, 16, 0, 0,
            15, 10, North, 12, 1, 0,
            11, 12, East, 17, 0, 0,  // seg 22-25: subsector 6, ledge B
            12, 17, South, 18, 0, 0,
            17, 16, West, 19, 0, 0,
            16, 11, North, 15, 1, 0));
        w.Lump("SSECTORS", Shorts(4, 0, 3, 4, 3, 7, 4, 10, 4, 14, 4, 18, 4, 22)); // seg count, first seg
        // Every partition points north, so its right (front, child 0) side is east.
        w.Lump("NODES", Shorts( // x, y, dx, dy, right bbox (top, bottom, left, right), left bbox, right child, left child
            128, 0, 256, 0, 0, -128, 128, 384, 128, 0, 128, 384, unchecked((short)0x8001), unchecked((short)0x8002),
            128, -128, 0, 256, 128, -128, 128, 384, 128, -128, -128, 128, 0, unchecked((short)0x8000),
            912, -128, 0, 256, 128, -128, 912, 1040, 128, -128, 656, 912, unchecked((short)0x8006), unchecked((short)0x8005), // 2: along L15
            640, -128, 0, 256, 128, -128, 640, 656, 128, -128, 512, 640, unchecked((short)0x8004), unchecked((short)0x8003),   // 3: along L8
            656, -128, 0, 256, 128, -128, 656, 1040, 128, -128, 512, 656, 2, 3,                                               // 4: along L12
            448, -128, 0, 256, 128, -128, 512, 1040, 128, -128, -128, 384, 4, 1));                                            // 5 (root): x = 448
        w.Lump("SECTORS", Concat(
            Sector(0, 128, "FLOOR1", "FLOOR2", 160),
            Sector(16, 112, "LAVA1", "FLOOR1", 208),
            Sector(0, 128, "FLOOR1", "FLOOR2", 144),    // 2: room C
            Sector(0, 0, "FLOOR2", "FLOOR2", 112),      // 3: door D, closed
            Sector(-16, 256, "FLOOR2", "F_SKY1", 255),  // 4: courtyard A
            Sector(64, 192, "FLOOR1", "F_SKY1", 192))); // 5: ledge B, raised 80 over A (T3.4a)
        w.Lump("REJECT", new byte[(6 * 6 + 7) / 8]); // all clear: every sector sees every other
        w.Lump("BLOCKMAP", BuildBlockmap(-136, -136, 10, 3, MapVertexes, MapLinedefs));
    }

    // ---- E1M2: the specials map (M5) ----
    //
    // Each M5 task adds its cases here (TASKS.md M5). T5.1, the p_spec.c lookup
    // helpers: a corridor (sector 0) with a row of SpecialsAlcoves alcoves
    // along its north side (sector 1 + i), each opening onto the corridor and
    // onto its neighbours through two-sided lines, so the corridor has 24
    // neighbours (more than p_spec.c's MAX_ADJOINING_SECTORS):
    //
    //  y = 128   +----+----+----+-- ... --+----+
    //            | a0 | a1 | a2 |         | a23|   alcoves, 32 wide
    //  y = 0     +----+----+----+-- ... --+----+
    //            |          corridor            |
    //  y = -128  +------------------------------+
    //            x = 0                          x = 768
    //
    // Lines: 0 corridor south (tag 5), 1 west, 2 east, 3 + i the opening of
    // alcove i (alcove in front), 27 + i alcove i's north wall (alcove 0's a
    // switch, SW1BRCOM), 51 and 52 the row's west and east ends, 52 + j the
    // boundary between alcoves j - 1 and j (j = 1..23, alcove j in front).
    // Alcoves 0-21 have floors 16..184 (steps of 8, shuffled; the lowest in
    // alcove 0), alcove 22 a floor of 8 (above the corridor's 0, but after
    // 22 higher neighbours, so P_FindNextHighestFloor's vanilla overflow
    // skips it) and alcove 23 one of -32. Ceilings: 256-280, alcove 22 96
    // (the lowest), alcove 23 320 (the highest). Lights 96-152, alcove 23 64.
    // Alcoves 3, 7 and 12 have tag 5. Nodes: the root splits along y = 0
    // (the corridor in front), then a chain along the alcove boundaries.

    /// <summary>The number of alcoves on E1M2 (T5.1).</summary>
    public const int SpecialsAlcoves = 24;

    /// <summary>E1M2's alcove floors (map units), alcove i is sector 1 + i (T5.1).</summary>
    public static int AlcoveFloor(int i) => i < 22 ? 16 + 8 * (i * 5 % 22) : i == 22 ? 8 : -32;

    /// <summary>E1M2's alcove ceilings.</summary>
    public static int AlcoveCeiling(int i) => i < 22 ? 256 + 8 * (i % 4) : i == 22 ? 96 : 320;

    /// <summary>E1M2's alcove light levels.</summary>
    public static int AlcoveLight(int i) => i < 23 ? 96 + 8 * (i % 8) : 64;

    /// <summary>E1M2's alcove tags (alcoves 3, 7 and 12 share tag 5 with line 0).</summary>
    public static int AlcoveTag(int i) => i is 3 or 7 or 12 ? 5 : 0;

    private static void BuildSpecialsMap(Writer w)
    {
        const int n = SpecialsAlcoves, width = 32;
        var vertexes = new List<short> { n * width, -128, 0, -128 }; // v0 corridor south-east, v1 south-west
        int Mid(int i) => 2 + i;            // (32 i, 0)
        int Top(int i) => 2 + (n + 1) + i;  // (32 i, 128)
        for (int i = 0; i <= n; i++)
            vertexes.AddRange(new[] { (short)(i * width), (short)0 });
        for (int i = 0; i <= n; i++)
            vertexes.AddRange(new[] { (short)(i * width), (short)128 });

        var lines = new List<short[]>(); // v1, v2, flags, special, tag, right, left
        var sides = new List<byte[]>();
        int Side(string upper, string lower, string middle, int sector)
        {
            sides.Add(Sidedef(upper, lower, middle, (short)sector));
            return sides.Count - 1;
        }
        void OneSided(int v1, int v2, int sector, string middle, int tag = 0) =>
            lines.Add(new[] { (short)v1, (short)v2, (short)1, (short)0, (short)tag, (short)Side("-", "-", middle, sector), (short)-1 });
        void TwoSided(int v1, int v2, int front, int back) =>
            lines.Add(new[] { (short)v1, (short)v2, TwoSidedFlag, (short)0, (short)0,
                (short)Side("BRICK1", "BRICK1", "-", front), (short)Side("BRICK1", "BRICK1", "-", back) });

        OneSided(0, 1, 0, "BRICK1", tag: 5);  // L0: corridor south (westwards)
        OneSided(1, Mid(0), 0, "BRICK1");     // L1: corridor west
        OneSided(Mid(n), 0, 0, "BRICK1");     // L2: corridor east
        for (int i = 0; i < n; i++)
            TwoSided(Mid(i + 1), Mid(i), 1 + i, 0); // L3 + i: alcove i's opening (westwards: the alcove in front)
        for (int i = 0; i < n; i++)
            OneSided(Top(i), Top(i + 1), 1 + i, i == 0 ? "SW1BRCOM" : "BRICK1"); // L27 + i: alcove north walls
        OneSided(Mid(0), Top(0), 1, "BRICK1");       // L51: the row's west end
        OneSided(Top(n), Mid(n), n, "BRICK1");       // L52: its east end
        for (int j = 1; j < n; j++)
            TwoSided(Mid(j), Top(j), 1 + j, j);      // L52 + j: alcoves j - 1 | j (northwards: alcove j in front)

        var segs = new List<short>();
        var subsectors = new List<short>();
        void Seg(int v1, int v2, int line, int side)
        {
            int x1 = vertexes[2 * v1], y1 = vertexes[2 * v1 + 1], x2 = vertexes[2 * v2], y2 = vertexes[2 * v2 + 1];
            short angle = unchecked((short)((int)Math.Round(Math.Atan2(y2 - y1, x2 - x1) / (2 * Math.PI) * 65536) & 0xffff));
            segs.AddRange(new[] { (short)v1, (short)v2, angle, (short)line, (short)side, (short)0 });
        }
        void Subsector(int first)
        {
            subsectors.Add((short)(segs.Count / 6 - first));
            subsectors.Add((short)first);
        }
        // Subsector 0: the corridor, clockwise from its south wall.
        Seg(0, 1, 0, 0);
        Seg(1, Mid(0), 1, 0);
        for (int i = 0; i < n; i++)
            Seg(Mid(i), Mid(i + 1), 3 + i, 1);
        Seg(Mid(n), 0, 2, 0);
        Subsector(0);
        // Subsector 1 + i: alcove i.
        for (int i = 0; i < n; i++)
        {
            int first = segs.Count / 6;
            Seg(Mid(i + 1), Mid(i), 3 + i, 0);
            if (i == 0)
                Seg(Mid(0), Top(0), 51, 0);
            else
                Seg(Mid(i), Top(i), 52 + i, 0);
            Seg(Top(i), Top(i + 1), 27 + i, 0);
            if (i == n - 1)
                Seg(Top(n), Mid(n), 52, 0);
            else
                Seg(Top(i + 1), Mid(i + 1), 52 + i + 1, 1);
            Subsector(first);
        }

        // Nodes: boundary j (northwards at x = 32 j, the east in front) at index n - 1 - j, its back child
        // alcove j - 1, its front child the node of boundary j + 1 (or the last alcove); the root (last)
        // splits along y = 0 eastwards, the corridor (south) in front.
        var nodes = new List<short>();
        for (int j = n - 1; j >= 1; j--)
        {
            int front = j == n - 1 ? 0x8000 | n : n - 2 - j;
            int back = 0x8000 | j;
            nodes.AddRange(new[]
            {
                (short)(j * width), (short)0, (short)0, (short)128,
                (short)128, (short)0, (short)(j * width), (short)(n * width), // right box: top, bottom, left, right
                (short)128, (short)0, (short)((j - 1) * width), (short)(j * width), // left box
                unchecked((short)front), unchecked((short)back),
            });
        }
        nodes.AddRange(new[]
        {
            (short)0, (short)0, (short)(n * width), (short)0,
            (short)0, (short)-128, (short)0, (short)(n * width),
            (short)128, (short)0, (short)0, (short)(n * width),
            unchecked((short)0x8000), (short)(n - 2),
        });

        var sectors = new List<byte[]> { Sector(0, 128, "FLOOR1", "FLOOR2", 160) };
        for (int i = 0; i < n; i++)
            sectors.Add(Sector((short)AlcoveFloor(i), (short)AlcoveCeiling(i), i % 2 == 0 ? "FLOOR2" : "LAVA1", "FLOOR1", (short)AlcoveLight(i), (short)AlcoveTag(i)));

        var linedefs = new short[lines.Count, 7];
        for (int i = 0; i < lines.Count; i++)
        {
            for (int k = 0; k < 7; k++)
                linedefs[i, k] = lines[i][k];
        }
        var flat = new List<short>();
        foreach (short[] l in lines)
            flat.AddRange(l);

        w.Markers("E1M2");
        w.Lump("THINGS", Shorts(64, -64, 90, 1, 7)); // player 1 start in the corridor
        w.Lump("LINEDEFS", Shorts(flat.ToArray()));
        w.Lump("SIDEDEFS", Concat(sides.ToArray()));
        w.Lump("VERTEXES", Shorts(vertexes.ToArray()));
        w.Lump("SEGS", Shorts(segs.ToArray()));
        w.Lump("SSECTORS", Shorts(subsectors.ToArray()));
        w.Lump("NODES", Shorts(nodes.ToArray()));
        w.Lump("SECTORS", Concat(sectors.ToArray()));
        w.Lump("REJECT", new byte[(sectors.Count * sectors.Count + 7) / 8]);
        w.Lump("BLOCKMAP", BuildBlockmap(-8, -136, 7, 3, vertexes.ToArray(), linedefs));
    }

    private const short TwoSidedFlag = Line.ML_TWOSIDED;

    private static byte[] Sidedef(string upper, string lower, string middle, short sector, short xOffset = 0, short yOffset = 0)
    {
        byte[] side = new byte[30];
        BinaryPrimitives.WriteInt16LittleEndian(side, xOffset);
        BinaryPrimitives.WriteInt16LittleEndian(side.AsSpan(2), yOffset);
        Encoding.ASCII.GetBytes(upper, side.AsSpan(4));
        Encoding.ASCII.GetBytes(lower, side.AsSpan(12));
        Encoding.ASCII.GetBytes(middle, side.AsSpan(20));
        BinaryPrimitives.WriteInt16LittleEndian(side.AsSpan(28), sector);
        return side;
    }

    private static byte[] Sector(short floor, short ceiling, string floorFlat, string ceilingFlat, short light, short tag = 0)
    {
        byte[] sector = new byte[26]; // floor, ceiling, floor flat, ceiling flat, light, special, tag
        BinaryPrimitives.WriteInt16LittleEndian(sector, floor);
        BinaryPrimitives.WriteInt16LittleEndian(sector.AsSpan(2), ceiling);
        Encoding.ASCII.GetBytes(floorFlat, sector.AsSpan(4));
        Encoding.ASCII.GetBytes(ceilingFlat, sector.AsSpan(12));
        BinaryPrimitives.WriteInt16LittleEndian(sector.AsSpan(20), light);
        BinaryPrimitives.WriteInt16LittleEndian(sector.AsSpan(24), tag);
        return sector;
    }

    /// <summary>
    /// A blockmap of <paramref name="width"/> × <paramref name="height"/> blocks
    /// of 128 from the origin: each block lists (after the customary 0) the
    /// linedefs whose bounding box touches it, which is exact for these
    /// axis-aligned lines.
    /// </summary>
    private static byte[] BuildBlockmap(short originX, short originY, short width, short height, short[] vertexes, short[,] linedefs)
    {
        var offsets = new List<short> { originX, originY, width, height };
        var lists = new List<short>();
        int listStart = 4 + width * height;
        for (int by = 0; by < height; by++)
        {
            for (int bx = 0; bx < width; bx++)
            {
                offsets.Add((short)(listStart + lists.Count));
                int left = originX + bx * 128, bottom = originY + by * 128;
                lists.Add(0);
                for (int i = 0; i < linedefs.GetLength(0); i++)
                {
                    short v1 = linedefs[i, 0], v2 = linedefs[i, 1];
                    int x1 = vertexes[2 * v1], y1 = vertexes[2 * v1 + 1], x2 = vertexes[2 * v2], y2 = vertexes[2 * v2 + 1];
                    if (Math.Max(x1, x2) >= left && Math.Min(x1, x2) <= left + 128 && Math.Max(y1, y2) >= bottom && Math.Min(y1, y2) <= bottom + 128)
                        lists.Add((short)i);
                }
                lists.Add(-1);
            }
        }
        offsets.AddRange(lists);
        return Shorts(offsets.ToArray());
    }

    private static byte[] Concat(params byte[][] parts)
    {
        var all = new List<byte>();
        foreach (byte[] part in parts)
            all.AddRange(part);
        return all.ToArray();
    }

    private static byte[] Shorts(params short[] values)
    {
        byte[] data = new byte[values.Length * 2];
        for (int i = 0; i < values.Length; i++)
            BinaryPrimitives.WriteInt16LittleEndian(data.AsSpan(i * 2), values[i]);
        return data;
    }

    // ---- Other lumps ----

    private static byte[] BuildEndoom()
    {
        byte[] lump = new byte[80 * 25 * 2];
        string text = "IsoDoom synthetic test IWAD - generated content, no id Software data";
        for (int i = 0; i < 80 * 25; i++)
        {
            lump[i * 2] = (byte)' ';
            lump[i * 2 + 1] = 0x1F; // white on blue
        }
        int start = 12 * 80 + (80 - text.Length) / 2;
        for (int i = 0; i < text.Length; i++)
            lump[(start + i) * 2] = (byte)text[i];
        return lump;
    }

    private static byte[] BuildDemo()
    {
        // v1.9 header: version, skill, episode, map, deathmatch, respawn, fast, nomonsters, consoleplayer, playeringame[4].
        var demo = new List<byte> { 109, 2, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0 };
        for (int tic = 0; tic < 35; tic++)
            demo.AddRange(new byte[] { 25, 0, (byte)(tic < 17 ? 2 : 0), 0 }); // forwardmove, sidemove, angleturn, buttons
        demo.Add(0x80); // DEMOMARKER
        return demo.ToArray();
    }

    private static byte[] BuildGenmidi()
    {
        // "#OPL_II#", 175 instruments of 36 bytes, 175 names of 32 bytes (all instruments silent).
        byte[] lump = new byte[8 + 175 * 36 + 175 * 32];
        Encoding.ASCII.GetBytes("#OPL_II#", lump);
        for (int i = 0; i < 175; i++)
            Encoding.ASCII.GetBytes($"Synthetic {i}", lump.AsSpan(8 + 175 * 36 + i * 32));
        return lump;
    }

    private static byte[] BuildMus()
    {
        // MUS: header, then two notes on channel 0 and the score end (event byte: last-in-group flag, type, channel).
        byte[] score =
        {
            0x90, 0x80 | 60, 100, 16, // play note 60 at volume 100; delay 16 tics
            0x80, 60, 16,             // release note 60; delay 16
            0x90, 64, 16,             // play note 64 (same volume); delay 16
            0x00, 64,                 // release note 64
            0x60,                     // score end
        };
        byte[] lump = new byte[16 + score.Length];
        Encoding.ASCII.GetBytes("MUS\x1A", lump);
        BinaryPrimitives.WriteUInt16LittleEndian(lump.AsSpan(4), (ushort)score.Length);
        BinaryPrimitives.WriteUInt16LittleEndian(lump.AsSpan(6), 16);
        BinaryPrimitives.WriteUInt16LittleEndian(lump.AsSpan(8), 1); // primary channels
        score.CopyTo(lump, 16);
        return lump;
    }

    private static byte[] BuildMidi()
    {
        byte[] track = { 0x00, 0x90, 60, 100, 0x60, 0x80, 60, 0, 0x00, 0xFF, 0x2F, 0x00 }; // note on, note off, end of track
        var midi = new List<byte>();
        midi.AddRange(Encoding.ASCII.GetBytes("MThd"));
        midi.AddRange(new byte[] { 0, 0, 0, 6, 0, 0, 0, 1, 0, 96 }); // format 0, 1 track, 96 ticks per quarter
        midi.AddRange(Encoding.ASCII.GetBytes("MTrk"));
        midi.AddRange(new byte[] { 0, 0, 0, (byte)track.Length });
        midi.AddRange(track);
        return midi.ToArray();
    }

    private static byte[] BuildDmxSound()
    {
        // DMX: format 3, 11025 Hz, sample count (incl. the 16 pad bytes either side), then 8-bit unsigned samples.
        const int samples = 2048;
        byte[] lump = new byte[8 + 16 + samples + 16];
        BinaryPrimitives.WriteUInt16LittleEndian(lump, 3);
        BinaryPrimitives.WriteUInt16LittleEndian(lump.AsSpan(2), 11025);
        BinaryPrimitives.WriteUInt32LittleEndian(lump.AsSpan(4), samples + 32);
        for (int i = 0; i < 16; i++)
        {
            lump[8 + i] = 128;
            lump[8 + 16 + samples + i] = 128;
        }
        for (int i = 0; i < samples; i++)
        {
            int amplitude = 100 * (samples - i) / samples;
            lump[8 + 16 + i] = (byte)(128 + ((i / 12) % 2 == 0 ? amplitude : -amplitude)); // decaying square wave
        }
        return lump;
    }

    private static byte[] BuildPcSpeakerSound()
    {
        // PC speaker: format 0, tone count, then one tone byte per 1/140 s.
        byte[] lump = new byte[4 + 20];
        BinaryPrimitives.WriteUInt16LittleEndian(lump.AsSpan(2), 20);
        for (int i = 0; i < 20; i++)
            lump[4 + i] = (byte)(60 - i * 2);
        return lump;
    }

    // ---- WAD writer ----

    private sealed class Writer
    {
        private readonly List<(string Name, byte[] Data)> _lumps = new();

        public void Lump(string name, byte[]? data = null) => _lumps.Add((name, data ?? Array.Empty<byte>()));

        public void Markers(params string[] names)
        {
            foreach (string name in names)
                Lump(name);
        }

        /// <summary>Header, lump data, then the directory (as id's tools lay it out).</summary>
        public byte[] Build()
        {
            int dataSize = 0;
            foreach ((_, byte[] data) in _lumps)
                dataSize += data.Length;
            byte[] wad = new byte[12 + dataSize + 16 * _lumps.Count];
            Encoding.ASCII.GetBytes("IWAD", wad);
            BinaryPrimitives.WriteInt32LittleEndian(wad.AsSpan(4), _lumps.Count);
            BinaryPrimitives.WriteInt32LittleEndian(wad.AsSpan(8), 12 + dataSize);
            int pos = 12;
            for (int i = 0; i < _lumps.Count; i++)
            {
                (string name, byte[] data) = _lumps[i];
                if (name.Length > 8)
                    throw new InvalidOperationException($"Lump name {name} is longer than 8 characters.");
                data.CopyTo(wad, pos);
                Span<byte> entry = wad.AsSpan(12 + dataSize + 16 * i, 16);
                BinaryPrimitives.WriteInt32LittleEndian(entry, data.Length == 0 ? 0 : pos);
                BinaryPrimitives.WriteInt32LittleEndian(entry[4..], data.Length);
                Encoding.ASCII.GetBytes(name, entry[8..]);
                pos += data.Length;
            }
            return wad;
        }
    }
}
