using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.Text;
using IsoDoom.Map;
using IsoDoom.Wad;
using IsoDoom.Wad.Graphics;

namespace IsoDoom.Tools.SyntheticIwad;

/// <summary>
/// A small synthetic IWAD for running the WAD viewer check in CI (T1.6b),
/// where no id Software WAD is available. Everything in it is generated here
/// (procedural palettes, patterns and shapes), so it holds no id data and can
/// be built anywhere; the output is deterministic.
/// <para>
/// It identifies as shareware Doom (<c>E1M1</c>, no <c>E3M1</c>) and has at
/// least one lump of every <see cref="LumpKind"/>: <c>PLAYPAL</c> (14
/// palettes) and <c>COLORMAP</c> (34 maps); <c>PNAMES</c>, <c>TEXTURE1</c> and
/// <c>TEXTURE2</c> with a single-patch, a multi-patch (overlapping, clipped
/// at the edges), a masked and a non-128-high texture; wall patches in
/// <c>P_START</c>/<c>P1_START</c> with a duplicate name (the later copy wins,
/// the earlier one is overridden); flats in <c>F_START</c>/<c>F1_START</c>;
/// sprites in <c>S_START</c> with a fully rotated frame (mirrored pairs) and
/// rotation-0 frames (one full bright in its spawn state, one for a thing
/// hanging from the ceiling), plus a sprite lump no sprite uses; global graphics
/// (title, status bar, menu, font glyphs, with offsets and transparency); a
/// map with a real BSP tree and every wall-section case (see <c>BuildMap</c>), and
/// <c>E1M2</c>, the specials map M5's tasks add their cases to (see
/// <c>BuildSpecialsMap</c>; a switch texture pair); ENDOOM, GENMIDI, DMXGUS, MUS and MIDI music, DMX and PC
/// speaker sounds, a demo and a plain text lump.
/// </para>
/// </summary>
public static class SyntheticIwad
{
    public const string DefaultFileName = "isodoom-synthetic.wad";

    /// <summary>The IWAD's bytes.</summary>
    public static byte[] Build()
    {
        var w = new Writer();
        w.Lump("PLAYPAL", BuildPlaypal());
        w.Lump("COLORMAP", BuildColormap());
        w.Lump("ENDOOM", BuildEndoom());
        w.Lump("DEMO1", BuildDemo());
        BuildMap(w);
        BuildSpecialsMap(w);
        w.Lump("TEXTURE1", BuildTextureLump(
            new Tex("NULLTEX", 64, 64, false, (0, 0, 0)), // texture 0 is never drawn (vanilla's AASTINKY/AASHITTY)
            new Tex("BRICK1", 64, 64, false, (0, 0, 0)),
            new Tex("BRKPNL", 128, 128, false, (0, 0, 0), (64, 0, 1), (-32, 64, 0), (32, 64, 0), (96, 64, 0)),
            new Tex("GRATE", 64, 64, true, (0, 0, 2), (32, 0, 2)),
            new Tex("PANEL", 64, 72, false, (0, -8, 1))));
        w.Lump("TEXTURE2", BuildTextureLump(
            new Tex("WINFRAME", 32, 64, false, (0, 0, 2)),
            new Tex("SW1BRCOM", 64, 128, false, (0, 0, 3)), // a switch pair of p_switch.c's list (T5.1, E1M2)
            new Tex("SW2BRCOM", 64, 128, false, (0, 0, 4)),
            // An animated wall texture of p_spec.c's animdefs, its three frames the bricks scrolled down (T5.7, E1M2).
            new Tex("SLADRIP1", 64, 64, false, (0, -64, 0), (0, 0, 0)),
            new Tex("SLADRIP2", 64, 64, false, (0, -48, 0), (0, 16, 0)),
            new Tex("SLADRIP3", 64, 64, false, (0, -32, 0), (0, 32, 0))));
        w.Lump("PNAMES", BuildPNames("WALLBRK", "WALLPNL", "WINDOW", "SWOFF", "SWON"));
        w.Lump("GENMIDI", BuildGenmidi());
        w.Lump("DMXGUS", Encoding.ASCII.GetBytes("# Synthetic test patch map\r\n0, 2, 1, 0, acpiano\r\n"));
        w.Lump("D_E1M1", BuildMus());
        w.Lump("D_INTRO", BuildMidi());
        w.Lump("DSPISTOL", BuildDmxSound());
        w.Lump("DPPISTOL", BuildPcSpeakerSound());
        w.Lump("README", Encoding.ASCII.GetBytes(
            "IsoDoom synthetic test IWAD. Generated by tools/SyntheticIwad for the WAD viewer check in CI.\n"
            + "All content is procedural; it contains no id Software data. Not a playable game.\n"));

        // Global graphics (found by structure, as the UI lumps are).
        w.Lump("TITLEPIC", EncodePatch(TitlePic()));
        w.Lump("STBAR", EncodePatch(StatusBar()));
        w.Lump("M_DOOM", EncodePatch(MenuLogo()));
        w.Lump("STCFN065", EncodePatch(Glyph(_glyphA)));
        w.Lump("STCFN066", EncodePatch(Glyph(_glyphB)));
        w.Lump("STCFN067", EncodePatch(Glyph(_glyphC)));

        w.Markers("S_START");
        Image troo = Arrow();
        w.Lump("TROOA1", EncodePatch(troo));
        w.Lump("TROOA2A8", EncodePatch(troo.Tinted(1)));
        w.Lump("TROOA3A7", EncodePatch(troo.Tinted(2)));
        w.Lump("TROOA4A6", EncodePatch(troo.Tinted(3)));
        w.Lump("TROOA5", EncodePatch(troo.Tinted(4)));
        w.Lump("BAR1A0", EncodePatch(Barrel(0)));
        w.Lump("BAR1B0", EncodePatch(Barrel(1)));
        w.Lump("XXXXA0", EncodePatch(Barrel(2))); // in no sprite name list: listed, but no sprite frame
        w.Lump("COLUA0", EncodePatch(Lamp()));      // floor lamp (MT_MISC31): a full-bright spawn frame
        w.Lump("GOR2A0", EncodePatch(Hanging()));   // hanging body (MT_MISC56): spawns on the ceiling
        // T5.8: E1M2's keys, a blue keycard and a yellow skull key, each blinking between A and a full-bright B.
        w.Lump("BKEYA0", EncodePatch(Key(false, Index(1, 2, 3), Index(3, 4, 3))));
        w.Lump("BKEYB0", EncodePatch(Key(false, Index(3, 4, 3), Index(5, 6, 3))));
        w.Lump("YSKUA0", EncodePatch(Key(true, Index(5, 5, 0), Index(7, 7, 1))));
        w.Lump("YSKUB0", EncodePatch(Key(true, Index(7, 7, 1), Index(7, 7, 3))));
        w.Markers("S_END");

        w.Markers("P_START", "P1_START");
        w.Lump("WALLBRK", EncodePatch(Bricks()));
        w.Lump("WALLPNL", EncodePatch(Panel(0)));
        w.Lump("WINDOW", EncodePatch(Window()));
        w.Lump("WALLPNL", EncodePatch(Panel(2))); // duplicate: this one wins, the first is overridden
        w.Lump("SWOFF", EncodePatch(Switch(false)));
        w.Lump("SWON", EncodePatch(Switch(true)));
        w.Markers("P1_END", "P_END");

        w.Markers("F_START", "F1_START");
        w.Lump("FLOOR1", Checker().Pixels);
        w.Lump("FLOOR2", Diagonal().Pixels);
        w.Lump("LAVA1", Waves(0).Pixels);
        // T5.7: p_spec.c's animated flats LAVA1-LAVA4 and NUKAGE1-NUKAGE3 (animdefs; E1M1 and E1M2 draw them).
        w.Lump("LAVA2", Waves(16).Pixels);
        w.Lump("LAVA3", Waves(32).Pixels);
        w.Lump("LAVA4", Waves(48).Pixels);
        w.Lump("NUKAGE1", Ooze(0).Pixels);
        w.Lump("NUKAGE2", Ooze(1).Pixels);
        w.Lump("NUKAGE3", Ooze(2).Pixels);
        w.Lump("F_SKY1", Solid(64, 64, (x, y) => Index(1, 2, 3)).Pixels); // the sky flat (r_sky.h SKYFLATNAME)
        w.Markers("F1_END", "F_END");
        return w.Build();
    }

    /// <summary>
    /// Checks that the IWAD loads as the viewer loads it and has what the viewer
    /// check is meant to exercise. Returns the problems found (empty when fine).
    /// </summary>
    public static List<string> Check(WadArchive wad)
    {
        var problems = new List<string>();
        IwadInfo info = IwadIdentification.D_IdentifyVersion(wad);
        if (info.GameMode != GameMode.shareware)
            problems.Add($"identifies as {info.GameMode}, expected shareware");
        var catalog = GraphicsCatalog.Load(wad);
        foreach (GraphicCategory c in Enum.GetValues<GraphicCategory>())
        {
            if (catalog.Count(c) == 0)
                problems.Add($"no {c} in the graphics catalog");
        }
        var kinds = new HashSet<LumpKind>();
        bool overridden = false;
        foreach (LumpEntry e in LumpDirectory.Build(wad))
        {
            kinds.Add(e.Kind);
            overridden |= e.IsOverridden;
        }
        foreach (LumpKind k in Enum.GetValues<LumpKind>())
        {
            if (!kinds.Contains(k))
                problems.Add($"no lump of kind {LumpDirectory.KindName(k)}");
        }
        if (!overridden)
            problems.Add("no overridden lump");
        // T7.8b: the OPL bank and the MUS song read as i_oplmusic.c and mus2mid.c would.
        if (Genmidi.TryRead(wad.W_CacheLumpName("GENMIDI").Span, out string? genmidiError) is not { HasNames: true })
            problems.Add($"GENMIDI does not read: {genmidiError ?? "names missing"}");
        if (MusSong.TryRead(wad.W_CacheLumpName("D_E1M1").Span, out string? musError) is not MusSong song)
            problems.Add($"D_E1M1 does not read: {musError}");
        else if (song.Events.Count != SongEvents || song.LengthTics != SongTics || song.Mus2MidError is not null)
            problems.Add($"D_E1M1 has {song.Events.Count} events over {song.LengthTics} tics, expected {SongEvents} over {SongTics}{(song.Mus2MidError is null ? "" : $"; mus2mid.c refuses it: {song.Mus2MidError}")}");
        try
        {
            var map = Level.Load(wad, "E1M1");
            if (map.Nodes.Length < 2 || map.Sectors.Length < 2)
                problems.Add($"E1M1 has {map.Nodes.Length} nodes and {map.Sectors.Length} sectors, expected a BSP tree over several sectors");
            var walls = WallSections.Build(map, catalog.Textures);
            if (walls.Missing.Count > 0)
                problems.Add($"E1M1 has missing wall textures: {string.Join(", ", walls.Missing)}");
            foreach (WallSectionKind k in Enum.GetValues<WallSectionKind>())
            {
                if (!Has(walls, s => s.Kind == k && s.Texture != 0))
                    problems.Add($"E1M1 has no textured {k} wall section");
            }
            if (!Has(walls, s => s.Kind == WallSectionKind.Upper && (s.Line.Flags & Line.ML_DONTPEGTOP) != 0 && s.Texture != 0))
                problems.Add("E1M1 has no upper unpegged wall");
            if (!Has(walls, s => s.Kind == WallSectionKind.Lower && (s.Line.Flags & Line.ML_DONTPEGBOTTOM) != 0 && s.Texture != 0))
                problems.Add("E1M1 has no lower unpegged wall");
            if (!Has(walls, s => s.BackSector is { CeilingPic: WallSections.SKYFLATNAME } && s.FrontSector.CeilingPic == WallSections.SKYFLATNAME))
                problems.Add("E1M1 has no line with a sky ceiling on both sides");
            if (!Has(walls, s => s.BackSector is { } b && b.FloorHeight == b.CeilingHeight))
                problems.Add("E1M1 has no closed door (a two-sided line onto a sector with no height)");
        }
        catch (WadFormatException e)
        {
            problems.Add($"E1M1 does not load: {e.Message}");
        }
        try
        {
            var specials = Level.Load(wad, "E1M2");
            if (specials.Sectors.Length != SpecialsSectors || specials.Sectors[0].Lines.Count != 3 + SpecialsAlcoves)
                problems.Add($"E1M2 has {specials.Sectors.Length} sectors, its corridor {specials.Sectors[0].Lines.Count} lines; expected {SpecialsSectors} and {3 + SpecialsAlcoves}");
            if (specials.Sectors[DoorSector].Lines.Count != 4 || specials.R_PointInSubsector(144 << 16, 196 << 16).Sector.Index != DoorSector)
                problems.Add("E1M2's door sector is not between its rooms");
            if (specials.R_PointInSubsector(352 << 16, 196 << 16).Sector.Index != TeleportRoom
                || specials.R_PointInSubsector(416 << 16, 196 << 16).Sector.Index != TeleportPad
                || specials.R_PointInSubsector(TeleportDestX << 16, TeleportDestY << 16).Sector.Tag != TeleportTag
                || specials.Lines[TeleportLine].Special != 97 || specials.Lines[TeleportLine].FrontSector?.Index != TeleportRoom)
                problems.Add("E1M2's teleporter is not set up (room T, the pad, line 86, the destination in room R)");
            var walls = WallSections.Build(specials, catalog.Textures);
            if (walls.Missing.Count > 0)
                problems.Add($"E1M2 has missing wall textures: {string.Join(", ", walls.Missing)}");
            if (!Has(walls, s => s.Texture != 0 && catalog.Textures.TextureDefs[s.Texture].Name == "SW1BRCOM"))
                problems.Add("E1M2 has no switch texture");
        }
        catch (WadFormatException e)
        {
            problems.Add($"E1M2 does not load: {e.Message}");
        }
        return problems;
    }

    private static bool Has(WallSections walls, Func<WallSection, bool> match)
    {
        foreach (WallSection s in walls.Sections)
        {
            if (match(s))
                return true;
        }
        return false;
    }

    // ---- Palette ----
    // Palette 0 is a 8x8x4 RGB grid: index = r | g << 3 | b << 6 (r, g in 0..7, b in 0..3).
    // No component reaches 255, which leaves the viewer check's background colours free.

    private static int Index(int r, int g, int b) => r | g << 3 | b << 6;

    private static (int R, int G, int B) BaseColor(int i) => ((i & 7) * 36, ((i >> 3) & 7) * 36, (i >> 6) * 84);

    private static byte[] BuildPlaypal()
    {
        // 0: normal; 1-8: red (damage, berserk); 9-12: gold (pickup); 13: green (radiation suit), as st_stuff.c numbers them.
        var tints = new List<(int R, int G, int B, int Num, int Den)> { (0, 0, 0, 0, 1) };
        for (int k = 1; k <= 8; k++)
            tints.Add((255, 0, 0, k, 9));
        for (int k = 1; k <= 4; k++)
            tints.Add((215, 186, 69, k, 8));
        tints.Add((0, 255, 0, 1, 8));

        byte[] lump = new byte[Playpal.PaletteSize * tints.Count];
        for (int p = 0; p < tints.Count; p++)
        {
            (int tr, int tg, int tb, int num, int den) = tints[p];
            for (int i = 0; i < 256; i++)
            {
                (int r, int g, int b) = BaseColor(i);
                int o = p * Playpal.PaletteSize + i * 3;
                lump[o] = (byte)(r + (tr - r) * num / den);
                lump[o + 1] = (byte)(g + (tg - g) * num / den);
                lump[o + 2] = (byte)(b + (tb - b) * num / den);
            }
        }
        return lump;
    }

    private static byte[] BuildColormap()
    {
        // 0-31: darker in 32 steps; 32: inverted greyscale (invulnerability); 33: all black.
        byte[] lump = new byte[Colormap.MapSize * 34];
        for (int m = 0; m < 32; m++)
        {
            for (int i = 0; i < 256; i++)
            {
                int r = i & 7, g = (i >> 3) & 7, b = i >> 6;
                lump[m * 256 + i] = (byte)Index((r * (32 - m) + 16) / 32, (g * (32 - m) + 16) / 32, (b * (32 - m) + 16) / 32);
            }
        }
        for (int i = 0; i < 256; i++)
        {
            (int r, int g, int b) = BaseColor(i);
            int inv = 255 - (r * 3 + g * 6 + b) / 10; // 0..255
            lump[32 * 256 + i] = (byte)Index((inv * 7 + 127) / 255, (inv * 7 + 127) / 255, (inv * 3 + 127) / 255);
        }
        return lump;
    }

    // ---- Images ----

    private sealed class Image
    {
        public readonly int Width, Height, Left, Top;
        public readonly byte[] Pixels;
        public readonly bool[] Opaque;

        public Image(int width, int height, int left = 0, int top = 0)
        {
            Width = width;
            Height = height;
            Left = left;
            Top = top;
            Pixels = new byte[width * height];
            Opaque = new bool[width * height];
        }

        public void Set(int x, int y, int index)
        {
            Pixels[y * Width + x] = (byte)index;
            Opaque[y * Width + x] = true;
        }

        /// <summary>A copy with the blue level shifted by <paramref name="step"/> (wrapping), so each rotation looks different.</summary>
        public Image Tinted(int step)
        {
            var copy = new Image(Width, Height, Left, Top);
            for (int p = 0; p < Pixels.Length; p++)
            {
                if (Opaque[p])
                    copy.Set(p % Width, p / Width, (Pixels[p] & 63) | ((((Pixels[p] >> 6) + step) & 3) << 6));
            }
            return copy;
        }
    }

    private static Image Solid(int width, int height, Func<int, int, int> color, int left = 0, int top = 0)
    {
        var img = new Image(width, height, left, top);
        for (int y = 0; y < height; y++)
        {
            for (int x = 0; x < width; x++)
                img.Set(x, y, color(x, y));
        }
        return img;
    }

    private static Image Bricks() => Solid(64, 64, (x, y) =>
    {
        int row = y / 16, bx = (x + (row % 2) * 16) % 32;
        if (y % 16 == 15 || bx == 31)
            return Index(4, 4, 1); // mortar
        return Index(5 + (row + bx / 8) % 3, 1 + (y % 16) / 6, 0);
    });

    private static Image Panel(int hue) => Solid(64, 128, (x, y) =>
    {
        int edge = Math.Min(Math.Min(x, 63 - x), Math.Min(y % 64, 63 - y % 64));
        int level = edge < 2 ? 7 : edge < 4 ? 2 : 3 + (y % 64) / 22;
        return Index(level, level, hue + (edge < 2 ? 1 : 0));
    });

    /// <summary>A switch: a panel with a plate in the middle, lit when <paramref name="on"/>.</summary>
    private static Image Switch(bool on) => Solid(64, 128, (x, y) =>
    {
        bool plate = x >= 20 && x < 44 && y >= 48 && y < 80;
        if (plate)
            return on ? Index(7, 6, 0) : Index(2, 1, 0);
        return Index(3 + (x / 16 + y / 32) % 2, 3, 1);
    });

    private static Image Window()
    {
        var img = new Image(32, 64);
        for (int y = 0; y < 64; y++)
        {
            for (int x = 0; x < 32; x++)
            {
                bool frame = x < 4 || x >= 28 || y < 4 || y >= 60 || (x >= 15 && x <= 16) || (y >= 30 && y <= 33);
                if (frame)
                    img.Set(x, y, Index(1 + x % 3, 3, 2));
            }
        }
        return img;
    }

    private static Image Checker() => Solid(64, 64, (x, y) => ((x / 8 + y / 8) % 2 == 0) ? Index(6, 6, 2) : Index(2, 2, 1));

    private static Image Diagonal() => Solid(64, 64, (x, y) => Index((x + y) / 16, 7 - (x + y) / 18, (x / 16) % 4));

    private static Image Waves(int phase) => Solid(64, 64, (x, y) =>
    {
        int t = (x * 3 + Tri(y * 4) + phase) % 64;
        return Index(7, t / 10, 0);
    });

    // Green blobs that drift with the frame (T5.7's animated flat).
    private static Image Ooze(int frame) => Solid(64, 64, (x, y) =>
    {
        int t = (Tri(x * 2 + frame * 21) + Tri(y * 2 + 11)) / 8;
        return Index(t % 3, 3 + t % 5, 0);
    });

    private static int Tri(int v) => Math.Abs(v % 64 - 32); // a triangle wave in integers

    private static Image TitlePic() => Solid(320, 200, (x, y) =>
    {
        // An isometric diamond grid over a vertical gradient.
        bool line = (x + 2 * y) % 32 < 2 || (x - 2 * y + 400) % 32 < 2;
        return line ? Index(7, 6, 1) : Index(y / 40, y / 50, 3 - y / 67);
    });

    private static Image StatusBar() => Solid(320, 32, (x, y) =>
    {
        bool box = x % 64 < 2 || y < 2 || y >= 30;
        return box ? Index(6, 6, 1) : Index(3, 3, 1 + (x / 64) % 2);
    });

    private static Image MenuLogo()
    {
        // A diamond outline with a transparent inside and outside, offsets as menu graphics have.
        var img = new Image(96, 40, -4, -2);
        for (int y = 0; y < 40; y++)
        {
            for (int x = 0; x < 96; x++)
            {
                int d = Math.Abs(x - 48) * 40 / 96 + Math.Abs(y - 20);
                if (d >= 14 && d <= 20)
                    img.Set(x, y, Index(7, d - 13, 0));
            }
        }
        return img;
    }

    private static readonly string[] _glyphA = ["..#..", ".#.#.", "#...#", "#####", "#...#", "#...#", "#...#"];
    private static readonly string[] _glyphB = ["####.", "#...#", "####.", "#...#", "#...#", "#...#", "####."];
    private static readonly string[] _glyphC = [".###.", "#...#", "#....", "#....", "#....", "#...#", ".###."];

    private static Image Glyph(string[] rows)
    {
        var img = new Image(rows[0].Length, rows.Length);
        for (int y = 0; y < rows.Length; y++)
        {
            for (int x = 0; x < rows[y].Length; x++)
            {
                if (rows[y][x] == '#')
                    img.Set(x, y, Index(7, 7 - y / 2, 0));
            }
        }
        return img;
    }

    private static Image Arrow()
    {
        // Asymmetric (points right, notch at the top), so a mirrored rotation is visibly mirrored. A foot
        // (rows 44-55) reaches 4 rows below the origin, as many of id's sprites do (T3.5).
        var img = new Image(41, 56, 20, 52);
        for (int y = 0; y < 56; y++)
        {
            for (int x = 0; x < 41; x++)
            {
                bool head = x >= 20 && Math.Abs(y - 28) <= 40 - x;
                bool shaft = x < 20 && y >= 22 && y <= 34;
                bool notch = y < 6 && x > 26;
                bool foot = y >= 44 && x >= 12 && x <= 24 + (y - 44) / 3;
                if ((head || shaft || foot) && !notch)
                    img.Set(x, y, Index(x / 6, 2 + y / 14, 1));
            }
        }
        return img;
    }

    private static Image Lamp()
    {
        // A post with a bright bulb; 3 rows below the origin.
        var img = new Image(15, 48, 7, 45);
        for (int y = 0; y < 48; y++)
        {
            for (int x = 0; x < 15; x++)
            {
                bool bulb = y < 12 && (x - 7) * (x - 7) + (y - 6) * (y - 6) <= 36;
                bool post = y >= 12 && Math.Abs(x - 7) <= (y >= 44 ? 6 : 2);
                if (bulb || post)
                    img.Set(x, y, bulb ? Index(7, 6 + (x + y) % 2, 1) : Index(2 + y % 3, 2, 2));
            }
        }
        return img;
    }

    private static Image Hanging()
    {
        // A rope and a hanging shape, asymmetric; its origin is near the bottom, as id's hanging sprites.
        var img = new Image(20, 60, 9, 58);
        for (int y = 0; y < 60; y++)
        {
            for (int x = 0; x < 20; x++)
            {
                bool rope = y < 20 && x >= 8 && x <= 10;
                bool body = y >= 20 && Math.Abs(x - 9) <= 3 + (y - 20) / 8 && !(y > 50 && x < 6);
                if (rope || body)
                    img.Set(x, y, rope ? Index(5, 5, 0) : Index(6, (x + 2 * y) % 4, 0));
            }
        }
        return img;
    }

    /// <summary>A key (T5.8): a card (a rectangle with a stripe) or a skull key (a round head on a shaft).</summary>
    private static Image Key(bool skull, int body, int detail)
    {
        var img = new Image(10, 14, 5, 12);
        for (int y = 0; y < 14; y++)
        {
            for (int x = 0; x < 10; x++)
            {
                bool part, mark;
                if (skull)
                {
                    part = (y < 7 && (x - 5) * (x - 5) + (y - 3) * (y - 3) <= 12) || (y >= 7 && Math.Abs(x - 5) <= 1) || (y >= 11 && x >= 5 && x <= 8);
                    mark = y == 3 && (x == 3 || x == 7);
                }
                else
                {
                    part = x >= 1 && x <= 8 && y >= 2;
                    mark = y >= 5 && y <= 6;
                }
                if (part)
                    img.Set(x, y, mark ? detail : body);
            }
        }
        return img;
    }

    private static Image Barrel(int frame)
    {
        var img = new Image(23, 32, 11, 30);
        for (int y = 0; y < 32; y++)
        {
            for (int x = 0; x < 23; x++)
            {
                bool rim = y < 3 || y >= 29;
                bool body = Math.Abs(x - 11) <= (rim ? 9 : 11);
                if (body)
                    img.Set(x, y, rim ? Index(4, 4, 2) : Index(1 + frame, 3 + (x + frame * 3) % 5, 0));
            }
        }
        return img;
    }

    /// <summary>Encodes a patch: header, column offsets, then each column's posts (opaque runs of up to 128 pixels).</summary>
    private static byte[] EncodePatch(Image img)
    {
        if (img.Height > 254)
            throw new ArgumentException("Tall patches need relative topdeltas; not generated here.");
        var body = new List<byte>();
        int dataStart = 8 + 4 * img.Width;
        int[] offsets = new int[img.Width];
        for (int x = 0; x < img.Width; x++)
        {
            offsets[x] = dataStart + body.Count;
            int y = 0;
            while (y < img.Height)
            {
                if (!img.Opaque[y * img.Width + x])
                {
                    y++;
                    continue;
                }
                int start = y;
                while (y < img.Height && y - start < 128 && img.Opaque[y * img.Width + x])
                    y++;
                body.Add((byte)start);
                body.Add((byte)(y - start));
                body.Add(0); // unused pad byte
                for (int p = start; p < y; p++)
                    body.Add(img.Pixels[p * img.Width + x]);
                body.Add(0); // unused pad byte
            }
            body.Add(0xFF);
        }
        byte[] lump = new byte[dataStart + body.Count];
        BinaryPrimitives.WriteInt16LittleEndian(lump, (short)img.Width);
        BinaryPrimitives.WriteInt16LittleEndian(lump.AsSpan(2), (short)img.Height);
        BinaryPrimitives.WriteInt16LittleEndian(lump.AsSpan(4), (short)img.Left);
        BinaryPrimitives.WriteInt16LittleEndian(lump.AsSpan(6), (short)img.Top);
        for (int x = 0; x < img.Width; x++)
            BinaryPrimitives.WriteInt32LittleEndian(lump.AsSpan(8 + 4 * x), offsets[x]);
        body.CopyTo(lump, dataStart);
        return lump;
    }

    // ---- Wall textures (r_data.c maptexture_t / mappatch_t) ----

    private sealed record Tex(string Name, int Width, int Height, bool Masked, params (int X, int Y, int Patch)[] Patches);

    private static byte[] BuildPNames(params string[] names)
    {
        byte[] lump = new byte[4 + 8 * names.Length];
        BinaryPrimitives.WriteInt32LittleEndian(lump, names.Length);
        for (int i = 0; i < names.Length; i++)
            Encoding.ASCII.GetBytes(names[i], lump.AsSpan(4 + 8 * i));
        return lump;
    }

    private static byte[] BuildTextureLump(params Tex[] textures)
    {
        var body = new List<byte>();
        int dirSize = 4 + 4 * textures.Length;
        byte[] dir = new byte[dirSize];
        BinaryPrimitives.WriteInt32LittleEndian(dir, textures.Length);
        for (int i = 0; i < textures.Length; i++)
        {
            Tex t = textures[i];
            BinaryPrimitives.WriteInt32LittleEndian(dir.AsSpan(4 + 4 * i), dirSize + body.Count);
            byte[] mt = new byte[22 + 10 * t.Patches.Length];
            Encoding.ASCII.GetBytes(t.Name, mt);
            BinaryPrimitives.WriteInt32LittleEndian(mt.AsSpan(8), t.Masked ? 1 : 0);
            BinaryPrimitives.WriteInt16LittleEndian(mt.AsSpan(12), (short)t.Width);
            BinaryPrimitives.WriteInt16LittleEndian(mt.AsSpan(14), (short)t.Height);
            BinaryPrimitives.WriteInt16LittleEndian(mt.AsSpan(20), (short)t.Patches.Length);
            for (int j = 0; j < t.Patches.Length; j++)
            {
                Span<byte> mp = mt.AsSpan(22 + 10 * j);
                BinaryPrimitives.WriteInt16LittleEndian(mp, (short)t.Patches[j].X);
                BinaryPrimitives.WriteInt16LittleEndian(mp[2..], (short)t.Patches[j].Y);
                BinaryPrimitives.WriteInt16LittleEndian(mp[4..], (short)t.Patches[j].Patch);
                BinaryPrimitives.WriteInt16LittleEndian(mp[6..], 1); // stepdir (unused)
            }
            body.AddRange(mt);
        }
        byte[] lump = new byte[dirSize + body.Count];
        dir.CopyTo(lump, 0);
        body.CopyTo(lump, dirSize);
        return lump;
    }

    // ---- Map: two rooms, three subsectors under two BSP nodes, and a wall-section test strip ----
    //
    //  (-128,128) v0 ---L0--- v1 (128,128) ---L4--- v4 (384,128)
    //       |                  |                       |
    //       L3   west room     L1   east room, north   L5      y = 0: partition of
    //       |    sector 0      |    subsector 2        |       node 0 (no linedef),
    //       |    subsector 0   v7 - - - - - - - - - -  v6      split vertices v6, v7
    //       |                  |    east room, south   |
    //       |                  |    subsector 1        |
    // (-128,-128) v3 ---L2--- v2 (128,-128) ---L6--- v5 (384,-128)
    //
    // L1 is two-sided (the east room is raised 16 and its ceiling 16 lower, so
    // the west side has upper and lower textures; the east side has a masked
    // GRATE). Node 1 splits along L1, node 0 splits the east room at y = 0, so
    // the east subsectors each have an edge with no seg on it, as real node
    // builders make them. Linedefs run clockwise around each room, so their
    // right (front) sides face in.
    //
    // East of x = 448 (the root node's partition, no linedef), a separate strip
    // covers the other wall-section cases (T2.3), one sector per subsector:
    //
    //  v8 --L7-- v9 -L11- v10 -----L14----- v11 --L17-- v12      y = 128
    //  |         |   D    |                 |           |
    //  L10  C    L8 door  L12   A courtyard L15  B ledge L18
    //  |         |        |     (sky)       |   (sky)   |
    //  v13 -L9-- v14 -L13- v15 ----L16----- v16 --L19-- v17      y = -128
    //  x = 512   640      656               912         1040
    //
    // C (sector 2): a room, floor 0, ceiling 128; its west wall is lower
    // unpegged with a y offset. D (sector 3): a closed door (floor = ceiling =
    // 0), so L8 gives C a pegged upper and L12 gives A an upper and lower
    // unpegged pair. A (sector 4) and B (sector 5) have F_SKY1 ceilings at
    // 256 and 192, so L15 has no upper on A's side (the sky rule) although
    // its texture is "-"; L15 has a lower (unpegged, so anchored at the back
    // ceiling by the sky rule) and a masked GRATE (unpegged) on both sides.
    // B's floor (64) is 80 above A's, more than the cutaway's cutoff (32), so
    // a centre in A just west of L15 has B's floor cut and capped (T3.4a).
    private static readonly short[] _mapVertexes =
    [
        -128, 128, 128, 128, 128, -128, -128, -128, // v0-v3: west room
        384, 128, 384, -128,                        // v4, v5: east room
        384, 0, 128, 0,                             // v6, v7: where node 0's partition splits L5 and L1
        512, 128, 640, 128, 656, 128, 912, 128, 1040, 128,      // v8-v12: the strip's north edge
        512, -128, 640, -128, 656, -128, 912, -128, 1040, -128, // v13-v17: its south edge
    ];

    private const short TwoSided = Line.ML_TWOSIDED, PegTop = Line.ML_DONTPEGTOP, PegBottom = Line.ML_DONTPEGBOTTOM;

    // v1, v2, flags, special, tag, right side, left side (-1: none)
    private static readonly short[,] _mapLinedefs =
    {
        { 0, 1, 1, 11, 0, 0, -1 }, // L0: west room north, an S1 exit (11, T5.8: player 1 faces it from its start)
        { 1, 2, 4, 0, 0, 1, 2 },  // L1: two-sided, west room in front, east room behind
        { 2, 3, 1, 0, 0, 3, -1 }, // L2: west room south
        { 3, 0, 1, 0, 0, 4, -1 }, // L3: west room west
        { 1, 4, 1, 0, 0, 5, -1 }, // L4: east room north
        { 4, 5, 1, 0, 0, 6, -1 }, // L5: east room east
        { 5, 2, 1, 0, 0, 7, -1 }, // L6: east room south
        { 8, 9, 1, 0, 0, 8, -1 },                              // L7: C north
        { 9, 14, TwoSided, 1, 0, 9, 10 },                      // L8: C | door D (a DR door special)
        { 14, 13, 1, 0, 0, 11, -1 },                           // L9: C south
        { 13, 8, 1 | PegBottom, 0, 0, 12, -1 },                // L10: C west, lower unpegged
        { 9, 10, 1 | PegBottom, 0, 0, 13, -1 },                // L11: door track north (no height while closed)
        { 10, 15, TwoSided | PegTop | PegBottom, 0, 0, 14, 15 }, // L12: door D | courtyard A, both unpegged
        { 15, 14, 1 | PegBottom, 0, 0, 16, -1 },               // L13: door track south
        { 10, 11, 1, 0, 0, 17, -1 },                           // L14: A north
        { 11, 16, TwoSided | PegBottom, 0, 0, 18, 19 },        // L15: A | B, sky on both sides, masked GRATE
        { 16, 15, 1, 0, 0, 20, -1 },                           // L16: A south
        { 11, 12, 1, 0, 0, 21, -1 },                           // L17: B north
        { 12, 17, 1, 0, 0, 22, -1 },                           // L18: B east
        { 17, 16, 1, 0, 0, 23, -1 },                           // L19: B south
    };

    private static void BuildMap(Writer w)
    {
        w.Markers("E1M1");
        w.Lump("THINGS", Shorts( // x, y, angle, type, flags (all skills)
            0, 0, 90, 1, 7,           // player 1 start
            64, 64, 0, 2035, 7,       // barrel (BAR1)
            320, 64, 180, 3001, 7,    // imp (TROO), in the east room's north subsector

            // T3.5: imps facing the other seven directions (every rotation and mirror from any one
            // view), a full-bright lamp and a thing hanging from room C's ceiling.
            -80, 80, 0, 3001, 7,
            -80, 0, 45, 3001, 7,
            -80, -80, 90, 3001, 7,
            0, -80, 135, 3001, 7,
            80, -80, 225, 3001, 7,
            80, 0, 270, 3001, 7,
            0, 80, 315, 3001, 7,
            784, 0, 0, 2028, 7,       // floor lamp (COLU, full bright) in courtyard A
            576, 0, 0, 59, 7));       // hanging body (GOR2, MF_SPAWNCEILING) in room C
        var linedefs = new List<short>();
        for (int i = 0; i < _mapLinedefs.GetLength(0); i++)
        {
            for (int j = 0; j < _mapLinedefs.GetLength(1); j++)
                linedefs.Add(_mapLinedefs[i, j]);
        }
        w.Lump("LINEDEFS", Shorts([.. linedefs]));
        w.Lump("SIDEDEFS", Concat(
            Sidedef("-", "-", "BRICK1", 0),         // 0: L0
            Sidedef("PANEL", "PANEL", "-", 0),      // 1: L1 front (west room): upper and lower
            Sidedef("-", "-", "GRATE", 1),          // 2: L1 back (east room): masked, pegged
            Sidedef("-", "-", "BRKPNL", 0, 32),     // 3: L2, with an x offset
            Sidedef("-", "-", "BRICK1", 0),         // 4: L3
            Sidedef("-", "-", "BRKPNL", 1),         // 5: L4
            Sidedef("-", "-", "BRICK1", 1, 0, 8),   // 6: L5, with a y offset
            Sidedef("-", "-", "BRKPNL", 1),         // 7: L6
            Sidedef("-", "-", "BRICK1", 2),         // 8: L7
            Sidedef("PANEL", "-", "-", 2),          // 9: L8 front (C): pegged upper; no lower (same floors)
            Sidedef("-", "-", "-", 3),              // 10: L8 back (door): nothing to draw
            Sidedef("-", "-", "BRICK1", 2),         // 11: L9
            Sidedef("-", "-", "BRICK1", 2, 0, 8),   // 12: L10, lower unpegged with a y offset
            Sidedef("-", "-", "-", 3),              // 13: L11: "-", but no height while the door is closed
            Sidedef("-", "-", "-", 3),              // 14: L12 front (door): nothing to draw
            Sidedef("PANEL", "BRICK1", "-", 4, 16, 4), // 15: L12 back (A): unpegged upper and lower, offsets
            Sidedef("-", "-", "BRICK1", 3),         // 16: L13
            Sidedef("-", "-", "BRKPNL", 4),         // 17: L14
            Sidedef("-", "BRKPNL", "GRATE", 4, 8, 8), // 18: L15 front (A): no upper (sky), lower, masked
            Sidedef("-", "-", "GRATE", 5),          // 19: L15 back (B): masked only
            Sidedef("-", "-", "BRKPNL", 4),         // 20: L16
            Sidedef("-", "-", "BRICK1", 5),         // 21: L17
            Sidedef("-", "-", "BRICK1", 5),         // 22: L18
            Sidedef("-", "-", "BRICK1", 5)));       // 23: L19
        w.Lump("VERTEXES", Shorts(_mapVertexes));
        const short East = 0, North = 0x4000, West = unchecked((short)0x8000), South = unchecked((short)0xC000);
        w.Lump("SEGS", Shorts( // v1, v2, angle (BAM >> 16), linedef, side (0 front, 1 back), offset along the linedef side
            0, 1, East, 0, 0, 0,     // seg 0-3: subsector 0, the west room
            1, 2, South, 1, 0, 0,
            2, 3, West, 2, 0, 0,
            3, 0, North, 3, 0, 0,
            6, 5, South, 5, 0, 128,  // seg 4-6: subsector 1, the east room's south half
            5, 2, West, 6, 0, 0,
            2, 7, North, 1, 1, 0,
            7, 1, North, 1, 1, 128,  // seg 7-9: subsector 2, the east room's north half
            1, 4, East, 4, 0, 0,
            4, 6, South, 5, 0, 0,
            8, 9, East, 7, 0, 0,     // seg 10-13: subsector 3, room C
            9, 14, South, 8, 0, 0,
            14, 13, West, 9, 0, 0,
            13, 8, North, 10, 0, 0,
            9, 10, East, 11, 0, 0,   // seg 14-17: subsector 4, door D
            10, 15, South, 12, 0, 0,
            15, 14, West, 13, 0, 0,
            14, 9, North, 8, 1, 0,
            10, 11, East, 14, 0, 0,  // seg 18-21: subsector 5, courtyard A
            11, 16, South, 15, 0, 0,
            16, 15, West, 16, 0, 0,
            15, 10, North, 12, 1, 0,
            11, 12, East, 17, 0, 0,  // seg 22-25: subsector 6, ledge B
            12, 17, South, 18, 0, 0,
            17, 16, West, 19, 0, 0,
            16, 11, North, 15, 1, 0));
        w.Lump("SSECTORS", Shorts(4, 0, 3, 4, 3, 7, 4, 10, 4, 14, 4, 18, 4, 22)); // seg count, first seg
        // Every partition points north, so its right (front, child 0) side is east.
        w.Lump("NODES", Shorts( // x, y, dx, dy, right bbox (top, bottom, left, right), left bbox, right child, left child
            128, 0, 256, 0, 0, -128, 128, 384, 128, 0, 128, 384, unchecked((short)0x8001), unchecked((short)0x8002),
            128, -128, 0, 256, 128, -128, 128, 384, 128, -128, -128, 128, 0, unchecked((short)0x8000),
            912, -128, 0, 256, 128, -128, 912, 1040, 128, -128, 656, 912, unchecked((short)0x8006), unchecked((short)0x8005), // 2: along L15
            640, -128, 0, 256, 128, -128, 640, 656, 128, -128, 512, 640, unchecked((short)0x8004), unchecked((short)0x8003),   // 3: along L8
            656, -128, 0, 256, 128, -128, 656, 1040, 128, -128, 512, 656, 2, 3,                                               // 4: along L12
            448, -128, 0, 256, 128, -128, 512, 1040, 128, -128, -128, 384, 4, 1));                                            // 5 (root): x = 448
        w.Lump("SECTORS", Concat(
            Sector(0, 128, "FLOOR1", "FLOOR2", 160),
            Sector(16, 112, "LAVA1", "FLOOR1", 208),
            Sector(0, 128, "FLOOR1", "FLOOR2", 144),    // 2: room C
            Sector(0, 0, "FLOOR2", "FLOOR2", 112),      // 3: door D, closed
            Sector(-16, 256, "FLOOR2", "F_SKY1", 255),  // 4: courtyard A
            Sector(64, 192, "FLOOR1", "F_SKY1", 192))); // 5: ledge B, raised 80 over A (T3.4a)
        w.Lump("REJECT", new byte[(6 * 6 + 7) / 8]); // all clear: every sector sees every other
        w.Lump("BLOCKMAP", BuildBlockmap(-136, -136, 10, 3, _mapVertexes, _mapLinedefs));
    }

    // ---- E1M2: the specials map (M5) ----
    //
    // Each M5 task adds its cases here (TASKS.md M5). T5.1, the p_spec.c lookup
    // helpers: a corridor (sector 0) with a row of SpecialsAlcoves alcoves
    // along its north side (sector 1 + i), each opening onto the corridor and
    // onto its neighbours through two-sided lines, so the corridor has 24
    // neighbours (more than p_spec.c's MAX_ADJOINING_SECTORS):
    //
    //  y = 128   +----+----+----+-- ... --+----+
    //            | a0 | a1 | a2 |         | a23|   alcoves, 32 wide
    //  y = 0     +----+----+----+-- ... --+----+
    //            |          corridor            |
    //  y = -128  +------------------------------+
    //            x = 0                          x = 768
    //
    // Lines: 0 corridor south (tag 5), 1 west, 2 east, 3 + i the opening of
    // alcove i (alcove in front), 27 + i alcove i's north wall (alcove 0's a
    // switch, SW1BRCOM), 51 and 52 the row's west and east ends, 52 + j the
    // boundary between alcoves j - 1 and j (j = 1..23, alcove j in front).
    // Alcoves 0-21 have floors 16..184 (steps of 8, shuffled; the lowest in
    // alcove 0), alcove 22 a floor of 8 (above the corridor's 0, but after
    // 22 higher neighbours, so P_FindNextHighestFloor's vanilla overflow
    // skips it) and alcove 23 one of -32. Ceilings: 256-280, alcove 22 96
    // (the lowest), alcove 23 320 (the highest). Lights 96-152, alcove 23 64.
    // Alcoves 3, 7 and 12 have tag 5. Nodes: the root splits along y = 0
    // (the corridor in front), then a chain along the alcove boundaries.
    //
    // T5.2, line triggers (their effects are stubs until T5.3-T5.8): the
    // corridor's walls are use lines facing it, line 0 an SR button (63, tag
    // 5), line 1 an S1 switch (103, tag 5), line 2 an S1 switch whose tag (9)
    // no sector has; the openings of alcove 0 (line 3, floor 16) and alcove 22
    // (line 25, floor 8) are walk-over lines, a WR lift (88, which monsters
    // trigger too) and a W1 floor (38, players only), both tag 5.
    //
    // T5.3, doors: north of the row and apart from it (y = 152..240), room R
    // (sector 25, x = 0..128), a door (sector 26, x = 128..160, closed: floor
    // and ceiling 0, tag 6) and room S (sector 27, x = 160..288), floors 0 and
    // ceilings 128 (the door opens to 124). Lines 76 (R | door) and 77 (S |
    // door) are DR manual doors (1) facing the rooms; 78-85 the walls (78-80
    // R's, 81 and 82 the door's tracks, 83-85 S's). Subsectors 25-27; the
    // root node now splits along y = 144.
    //
    // T5.4, switches: lines 0 (SR) and 1 (S1) draw the switch texture
    // SW1BRCOM, line 27 (alcove 0's north wall, SW1BRCOM since T5.1) is an SR
    // raise-door button (63) of the door (tag 6). Line 2 stays BRICK1.
    //
    // T5.6, teleporters: east of room S and apart from it (y = 152..240), room
    // T (sector 28, x = 320..384, floor 0) and a teleporter pad P (sector 29,
    // x = 384..448, floor 8), ceilings 128. Line 86 (T | P, T in front) is a
    // WR teleport (97, tag 11) into room R (sector 25, tag 11 since T5.6), whose
    // teleport destination (thing 1, MT_TELEPORTMAN) stands at (64, 196)
    // facing east; 87-89 T's walls (south, west, north), 90-92 P's (south,
    // north, east). Subsectors 28 and 29; node n + 2 splits T from P along
    // x = 384, node n + 3 the door area from T along x = 304, and the root
    // (now n + 4) along y = 144.
    //
    // T5.7, lights and animations: alcoves 1, 2, 4, 5, 6, 8 and 9 have the
    // light specials 1, 2, 3, 8, 12, 13 and 17 (AlcoveSpecial); line 28
    // (alcove 1's north wall, BRKPNL) scrolls (48); line 29 (alcove 2's north
    // wall) draws the animated texture SLADRIP1 (frames SLADRIP1-3), room S
    // (sector 27) the animated flat NUKAGE1 (NUKAGE1-3); the odd alcoves'
    // LAVA1 animates too (LAVA1-4).
    //
    // T5.8, keys, damage floors, secrets and exits: alcoves 10, 11, 13, 14,
    // 15 and 16 have the sector specials 5 (hellslime, 10 damage), 7
    // (nukage, 5), 16 (super hellslime, 20), 4 (strobe hurt, 20, with a
    // fast strobe), 9 (a secret) and 11 (E1M8's exit floor). A blue keycard
    // (thing 2) and a yellow skull key (thing 3) lie in the corridor's east
    // half. Room S's east and north walls (lines 85 and 84) are an S1 exit
    // (11) and an S1 secret exit (51), both SW1BRCOM; alcove 23's opening
    // (line 26, a drop of 32 from the corridor) is a W1 exit (52) and the
    // boundary between alcoves 22 and 23 (line 75) a secret exit (124).

    /// <summary>E1M2's sector count: the corridor, the alcoves, rooms R and S with the door between (T5.3), room T and its teleporter pad (T5.6).</summary>
    public const int SpecialsSectors = 1 + SpecialsAlcoves + 3 + 2;

    /// <summary>E1M2's teleporter room T and pad P (T5.6): sectors 28 and 29, line 86 (T | P, T in front) a WR teleport (97) of tag <see cref="TeleportTag"/>.</summary>
    public const int TeleportRoom = SpecialsAlcoves + 4, TeleportPad = SpecialsAlcoves + 5, TeleportLine = 86;

    /// <summary>The tag of E1M2's teleport line and of room R (sector 25), where its destination stands (T5.6).</summary>
    public const short TeleportTag = 11;

    /// <summary>E1M2's teleport destination (T5.6): an <c>MT_TELEPORTMAN</c> in room R at (64, 196) facing east (angle 0).</summary>
    public const int TeleportDestX = 64, TeleportDestY = 196;

    /// <summary>E1M2's door sector (T5.3), between rooms R (sector 25) and S (27).</summary>
    public const int DoorSector = SpecialsAlcoves + 2;

    /// <summary>The tag of E1M2's door sector (line 27, alcove 0's SR button, has it since T5.4; tests give it to other lines).</summary>
    public const short DoorTag = 6;

    /// <summary>E1M2's door lines (T5.3): the door's sides facing R (front R) and S (front S), both DR manual doors (1).</summary>
    public const int DoorLineR = 76, DoorLineS = 77;

    /// <summary>The number of alcoves on E1M2 (T5.1).</summary>
    public const int SpecialsAlcoves = 24;

    /// <summary>E1M2's alcove floors (map units), alcove i is sector 1 + i (T5.1).</summary>
    public static int AlcoveFloor(int i) => i < 22 ? 16 + 8 * (i * 5 % 22) : i == 22 ? 8 : -32;

    /// <summary>E1M2's alcove ceilings.</summary>
    public static int AlcoveCeiling(int i) => i < 22 ? 256 + 8 * (i % 4) : i == 22 ? 96 : 320;

    /// <summary>E1M2's alcove light levels.</summary>
    public static int AlcoveLight(int i) => i < 23 ? 96 + 8 * (i % 8) : 64;

    /// <summary>
    /// E1M2's alcove sector specials (T5.7): the light specials of
    /// <c>P_SpawnSpecials</c>, alcove 1 flickering (1), 2 strobe fast (2), 4
    /// strobe slow (3), 5 glowing (8), 6 sync strobe slow (12), 8 sync strobe
    /// fast (13), 9 fire flicker (17); T5.8 the damage, secret and exit
    /// specials of <c>P_PlayerInSpecialSector</c>: alcove 10 hellslime (5),
    /// 11 nukage (7), 13 super hellslime (16), 14 strobe hurt (4, also a fast
    /// strobe), 15 a secret (9) and 16 the E1M8-style exit floor (11); none elsewhere.
    /// </summary>
    public static int AlcoveSpecial(int i) => i switch
    {
        1 => 1,
        2 => 2,
        4 => 3,
        5 => 8,
        6 => 12,
        8 => 13,
        9 => 17,
        10 => 5,
        11 => 7,
        13 => 16,
        14 => 4,
        15 => 9,
        16 => 11,
        _ => 0,
    };

    /// <summary>The alcove of each of E1M2's <c>P_PlayerInSpecialSector</c> specials (T5.8): sector 1 + alcove.</summary>
    public const int HellslimeAlcove = 10, NukageAlcove = 11, SuperHellslimeAlcove = 13, StrobeHurtAlcove = 14, SecretAlcove = 15, ExitFloorAlcove = 16;

    /// <summary>E1M2's exits (T5.8): line 85 an S1 exit (11), 84 an S1 secret exit (51), 26 a W1 exit (52), 75 a secret exit (124).</summary>
    public const int ExitSwitchLine = 85, SecretExitSwitchLine = 84, ExitWalkLine = 26, SecretExitWalkLine = 75;

    /// <summary>E1M2's keys (T5.8): a blue keycard at (560, -96) and a yellow skull key at (624, -96).</summary>
    public const int BlueCardX = 560, YellowSkullX = 624, KeysY = -96;

    /// <summary>The synthetic E1M1's exit (T5.8): line 0, the west room's north wall, an S1 exit (11) 128 units in front of player 1's start.</summary>
    public const int E1M1ExitLine = 0;

    /// <summary>E1M2's scrolling wall (T5.7): alcove 1's north wall, line 28 (special 48, <c>BRKPNL</c>).</summary>
    public const int ScrollLine = 28;

    /// <summary>E1M2's animated wall (T5.7): alcove 2's north wall, line 29 (<c>SLADRIP1</c>).</summary>
    public const int AnimatedWallLine = 29;

    /// <summary>E1M2's animated floor (T5.7): room S, sector 27 (<c>NUKAGE1</c>).</summary>
    public const int AnimatedFloorSector = SpecialsAlcoves + 3;

    /// <summary>E1M2's alcove tags (alcoves 3, 7 and 12 share tag 5 with line 0).</summary>
    public static int AlcoveTag(int i) => i is 3 or 7 or 12 ? 5 : 0;

    private static void BuildSpecialsMap(Writer w)
    {
        const int N = SpecialsAlcoves, Width = 32;
        var vertexes = new List<short> { N * Width, -128, 0, -128 }; // v0 corridor south-east, v1 south-west
        int Mid(int i) => 2 + i;            // (32 i, 0)
        int Top(int i) => 2 + (N + 1) + i;  // (32 i, 128)
        for (int i = 0; i <= N; i++)
            vertexes.AddRange([(short)(i * Width), (short)0]);
        for (int i = 0; i <= N; i++)
            vertexes.AddRange([(short)(i * Width), (short)128]);

        var lines = new List<short[]>(); // v1, v2, flags, special, tag, right, left
        var sides = new List<byte[]>();
        int Side(string upper, string lower, string middle, int sector)
        {
            sides.Add(Sidedef(upper, lower, middle, (short)sector));
            return sides.Count - 1;
        }
        void OneSided(int v1, int v2, int sector, string middle, int special = 0, int tag = 0) =>
            lines.Add([(short)v1, (short)v2, (short)1, (short)special, (short)tag, (short)Side("-", "-", middle, sector), (short)-1]);
        void TwoSided(int v1, int v2, int front, int back, int special = 0, int tag = 0) =>
            lines.Add([ (short)v1, (short)v2, TwoSidedFlag, (short)special, (short)tag,
                (short)Side("BRICK1", "BRICK1", "-", front), (short)Side("BRICK1", "BRICK1", "-", back) ]);

        OneSided(0, 1, 0, "SW1BRCOM", special: 63, tag: 5);  // L0: corridor south (westwards), SR raise door (a switch texture, T5.4)
        OneSided(1, Mid(0), 0, "SW1BRCOM", special: 103, tag: 5); // L1: corridor west, S1 open door (a switch texture, T5.4)
        OneSided(Mid(N), 0, 0, "BRICK1", special: 103, tag: 9); // L2: corridor east, S1 open door of no sector
        for (int i = 0; i < N; i++)
        {
            // L3 + i: alcove i's opening (westwards: the alcove in front); alcove 0's a WR lift
            // (monsters too), alcove 22's a W1 floor (players only).
            // T5.8: alcove 23's a W1 exit.
            (int special, int tag) = i switch { 0 => (88, 5), 22 => (38, 5), 23 => (52, 0), _ => (0, 0) };
            TwoSided(Mid(i + 1), Mid(i), 1 + i, 0, special, tag);
        }
        for (int i = 0; i < N; i++)
        {
            // L27 + i: alcove north walls; alcove 0's an SR raise-door button (63) of the door sector (T5.4),
            // alcove 1's a scrolling wall (48), alcove 2's an animated texture (T5.7).
            if (i == 0)
                OneSided(Top(i), Top(i + 1), 1 + i, "SW1BRCOM", special: 63, tag: DoorTag);
            else if (i == 1)
                OneSided(Top(i), Top(i + 1), 1 + i, "BRKPNL", special: 48);
            else if (i == 2)
                OneSided(Top(i), Top(i + 1), 1 + i, "SLADRIP1");
            else
                OneSided(Top(i), Top(i + 1), 1 + i, "BRICK1");
        }
        OneSided(Mid(0), Top(0), 1, "BRICK1");       // L51: the row's west end
        OneSided(Top(N), Mid(N), N, "BRICK1");       // L52: its east end
        for (int j = 1; j < N; j++)
            TwoSided(Mid(j), Top(j), 1 + j, j, special: j == N - 1 ? 124 : 0); // L52 + j: alcoves j - 1 | j (northwards: alcove j in front); L75 a secret exit (T5.8)

        // T5.3: a manual door (sector DoorSector) between rooms R (west) and S (east), apart from the rest.
        int doorV = vertexes.Count / 2;
        vertexes.AddRange([0, 152, 128, 152, 160, 152, 288, 152, 0, 240, 128, 240, 160, 240, 288, 240]);
        int a = doorV, b = doorV + 1, c = doorV + 2, e = doorV + 3, a2 = doorV + 4, b2 = doorV + 5, c2 = doorV + 6, e2 = doorV + 7;
        const int Room = DoorSector - 1, Door = DoorSector, Room2 = DoorSector + 1;
        void DoorLine(int v1, int v2, int front) =>
            lines.Add([ (short)v1, (short)v2, TwoSidedFlag, (short)1, (short)0,
                (short)Side("PANEL", "BRICK1", "-", front), (short)Side("BRICK1", "BRICK1", "-", Door) ]);
        DoorLine(b2, b, Room);                 // L76: R | door (southwards: R in front), DR manual door (1)
        DoorLine(c, c2, Room2);                // L77: S | door (northwards: S in front), DR manual door (1)
        OneSided(b, a, Room, "BRICK1");        // L78-L80: R's south, west and north walls
        OneSided(a, a2, Room, "BRICK1");
        OneSided(a2, b2, Room, "BRICK1");
        OneSided(c, b, Door, "BRICK1");        // L81, L82: the door's tracks (south, north)
        OneSided(b2, c2, Door, "BRICK1");
        OneSided(e, c, Room2, "BRICK1");       // L83-L85: S's south, north and east walls
        OneSided(c2, e2, Room2, "SW1BRCOM", special: 51); // T5.8: an S1 secret exit
        OneSided(e2, e, Room2, "SW1BRCOM", special: 11);  // T5.8: an S1 exit

        // T5.6: room T (west) and the teleporter pad P (east), apart from the rest.
        int teleV = vertexes.Count / 2;
        vertexes.AddRange([320, 152, 384, 152, 448, 152, 320, 240, 384, 240, 448, 240]);
        int f = teleV, g = teleV + 1, h = teleV + 2, f2 = teleV + 3, g2 = teleV + 4, h2 = teleV + 5;
        const int TeleRoom = TeleportRoom, Pad = TeleportPad;
        lines.Add([ (short)g2, (short)g, TwoSidedFlag, (short)97, TeleportTag,
            (short)Side("BRICK1", "BRICK1", "-", TeleRoom), (short)Side("BRICK1", "BRICK1", "-", Pad) ]); // L86: T | P (southwards: T in front), WR teleport
        OneSided(g, f, TeleRoom, "BRICK1");    // L87-L89: T's south, west and north walls
        OneSided(f, f2, TeleRoom, "BRICK1");
        OneSided(f2, g2, TeleRoom, "BRICK1");
        OneSided(h, g, Pad, "BRICK1");         // L90-L92: P's south, north and east walls
        OneSided(g2, h2, Pad, "BRICK1");
        OneSided(h2, h, Pad, "BRICK1");

        var segs = new List<short>();
        var subsectors = new List<short>();
        void Seg(int v1, int v2, int line, int side)
        {
            int x1 = vertexes[2 * v1], y1 = vertexes[2 * v1 + 1], x2 = vertexes[2 * v2], y2 = vertexes[2 * v2 + 1];
            short angle = unchecked((short)((int)Math.Round(Math.Atan2(y2 - y1, x2 - x1) / (2 * Math.PI) * 65536) & 0xffff));
            segs.AddRange([(short)v1, (short)v2, angle, (short)line, (short)side, (short)0]);
        }
        void Subsector(int first)
        {
            subsectors.Add((short)(segs.Count / 6 - first));
            subsectors.Add((short)first);
        }
        // Subsector 0: the corridor, clockwise from its south wall.
        Seg(0, 1, 0, 0);
        Seg(1, Mid(0), 1, 0);
        for (int i = 0; i < N; i++)
            Seg(Mid(i), Mid(i + 1), 3 + i, 1);
        Seg(Mid(N), 0, 2, 0);
        Subsector(0);
        // Subsector 1 + i: alcove i.
        for (int i = 0; i < N; i++)
        {
            int first = segs.Count / 6;
            Seg(Mid(i + 1), Mid(i), 3 + i, 0);
            if (i == 0)
                Seg(Mid(0), Top(0), 51, 0);
            else
                Seg(Mid(i), Top(i), 52 + i, 0);
            Seg(Top(i), Top(i + 1), 27 + i, 0);
            if (i == N - 1)
                Seg(Top(N), Mid(N), 52, 0);
            else
                Seg(Top(i + 1), Mid(i + 1), 52 + i + 1, 1);
            Subsector(first);
        }
        // Subsectors 25-27 (T5.3): rooms R and S and the door between them, each clockwise.
        Seg(b, a, 78, 0);
        Seg(a, a2, 79, 0);
        Seg(a2, b2, 80, 0);
        Seg(b2, b, 76, 0);
        Subsector(segs.Count / 6 - 4);
        Seg(c, b, 81, 0);
        Seg(b, b2, 76, 1);
        Seg(b2, c2, 82, 0);
        Seg(c2, c, 77, 1);
        Subsector(segs.Count / 6 - 4);
        Seg(e, c, 83, 0);
        Seg(c, c2, 77, 0);
        Seg(c2, e2, 84, 0);
        Seg(e2, e, 85, 0);
        Subsector(segs.Count / 6 - 4);
        // Subsectors 28 and 29 (T5.6): room T and the pad, each clockwise.
        Seg(g, f, 87, 0);
        Seg(f, f2, 88, 0);
        Seg(f2, g2, 89, 0);
        Seg(g2, g, TeleportLine, 0);
        Subsector(segs.Count / 6 - 4);
        Seg(h, g, 90, 0);
        Seg(g, g2, TeleportLine, 1);
        Seg(g2, h2, 91, 0);
        Seg(h2, h, 92, 0);
        Subsector(segs.Count / 6 - 4);

        // Nodes: boundary j (northwards at x = 32 j, the east in front) at index n - 1 - j, its back child
        // alcove j - 1, its front child the node of boundary j + 1 (or the last alcove); the root (last)
        // splits along y = 0 eastwards, the corridor (south) in front.
        var nodes = new List<short>();
        for (int j = N - 1; j >= 1; j--)
        {
            int front = j == N - 1 ? 0x8000 | N : N - 2 - j;
            int back = 0x8000 | j;
            nodes.AddRange(
            [
                (short)(j * Width), (short)0, (short)0, (short)128,
                (short)128, (short)0, (short)(j * Width), (short)(N * Width), // right box: top, bottom, left, right
                (short)128, (short)0, (short)((j - 1) * Width), (short)(j * Width), // left box
                unchecked((short)front), unchecked((short)back),
            ]);
        }
        nodes.AddRange(
        [
            (short)0, (short)0, (short)(N * Width), (short)0,
            (short)0, (short)-128, (short)0, (short)(N * Width),
            (short)128, (short)0, (short)0, (short)(N * Width),
            unchecked((short)0x8000), (short)(N - 2),
        ]);
        // T5.3: the door area north of the row; node n along x = 160 (the door west, S east), n + 1 along
        // x = 128 (R west); the root (n + 2) along y = 144 eastwards, the corridor and alcoves (node n - 1) in front.
        nodes.AddRange(
        [
            160, 152, 0, 88, 240, 152, 160, 288, 240, 152, 128, 160, unchecked((short)(0x8000 | Room2)), unchecked((short)(0x8000 | Door)),
            128, 152, 0, 88, 240, 152, 128, 288, 240, 152, 0, 128, (short)N, unchecked((short)(0x8000 | Room)),
            // T5.6: node n + 2 along x = 384 (T west, the pad east), n + 3 along x = 304 (the door area west, T east).
            384, 152, 0, 88, 240, 152, 384, 448, 240, 152, 320, 384, unchecked((short)(0x8000 | Pad)), unchecked((short)(0x8000 | TeleRoom)),
            304, 152, 0, 88, 240, 152, 320, 448, 240, 152, 0, 288, (short)(N + 2), (short)(N + 1),
            0, 144, (short)(N * Width), 0, 128, -128, 0, (short)(N * Width), 240, 152, 0, 448, (short)(N - 1), (short)(N + 3),
        ]);

        var sectors = new List<byte[]> { Sector(0, 128, "FLOOR1", "FLOOR2", 160) };
        for (int i = 0; i < N; i++)
            sectors.Add(Sector((short)AlcoveFloor(i), (short)AlcoveCeiling(i), i % 2 == 0 ? "FLOOR2" : "LAVA1", "FLOOR1", (short)AlcoveLight(i), (short)AlcoveTag(i),
                (short)AlcoveSpecial(i)));
        sectors.Add(Sector(0, 128, "FLOOR1", "FLOOR2", 160, TeleportTag)); // 25: room R (the teleport destination's, T5.6)
        sectors.Add(Sector(0, 0, "FLOOR2", "FLOOR2", 128, DoorTag));      // 26: the door, closed
        sectors.Add(Sector(0, 128, "NUKAGE1", "FLOOR2", 144));             // 27: room S (an animated flat, T5.7)
        sectors.Add(Sector(0, 128, "FLOOR1", "FLOOR2", 176));              // 28: room T (T5.6)
        sectors.Add(Sector(8, 128, "LAVA1", "FLOOR2", 208));               // 29: the teleporter pad

        short[,] linedefs = new short[lines.Count, 7];
        for (int i = 0; i < lines.Count; i++)
        {
            for (int k = 0; k < 7; k++)
                linedefs[i, k] = lines[i][k];
        }
        var flat = new List<short>();
        foreach (short[] l in lines)
            flat.AddRange(l);

        w.Markers("E1M2");
        w.Lump("THINGS", Shorts(64, -64, 90, 1, 7, TeleportDestX, TeleportDestY, 0, 14, 7, // player 1 start in the corridor; the teleport destination (T5.6)
            BlueCardX, KeysY, 0, 5, 7, YellowSkullX, KeysY, 0, 39, 7));                          // a blue keycard and a yellow skull key (T5.8)
        w.Lump("LINEDEFS", Shorts([.. flat]));
        w.Lump("SIDEDEFS", Concat([.. sides]));
        w.Lump("VERTEXES", Shorts([.. vertexes]));
        w.Lump("SEGS", Shorts([.. segs]));
        w.Lump("SSECTORS", Shorts([.. subsectors]));
        w.Lump("NODES", Shorts([.. nodes]));
        w.Lump("SECTORS", Concat([.. sectors]));
        w.Lump("REJECT", new byte[(sectors.Count * sectors.Count + 7) / 8]);
        w.Lump("BLOCKMAP", BuildBlockmap(-8, -136, 7, 3, [.. vertexes], linedefs));
    }

    private const short TwoSidedFlag = Line.ML_TWOSIDED;

    private static byte[] Sidedef(string upper, string lower, string middle, short sector, short xOffset = 0, short yOffset = 0)
    {
        byte[] side = new byte[30];
        BinaryPrimitives.WriteInt16LittleEndian(side, xOffset);
        BinaryPrimitives.WriteInt16LittleEndian(side.AsSpan(2), yOffset);
        Encoding.ASCII.GetBytes(upper, side.AsSpan(4));
        Encoding.ASCII.GetBytes(lower, side.AsSpan(12));
        Encoding.ASCII.GetBytes(middle, side.AsSpan(20));
        BinaryPrimitives.WriteInt16LittleEndian(side.AsSpan(28), sector);
        return side;
    }

    private static byte[] Sector(short floor, short ceiling, string floorFlat, string ceilingFlat, short light, short tag = 0, short special = 0)
    {
        byte[] sector = new byte[26]; // floor, ceiling, floor flat, ceiling flat, light, special, tag
        BinaryPrimitives.WriteInt16LittleEndian(sector, floor);
        BinaryPrimitives.WriteInt16LittleEndian(sector.AsSpan(2), ceiling);
        Encoding.ASCII.GetBytes(floorFlat, sector.AsSpan(4));
        Encoding.ASCII.GetBytes(ceilingFlat, sector.AsSpan(12));
        BinaryPrimitives.WriteInt16LittleEndian(sector.AsSpan(20), light);
        BinaryPrimitives.WriteInt16LittleEndian(sector.AsSpan(22), special);
        BinaryPrimitives.WriteInt16LittleEndian(sector.AsSpan(24), tag);
        return sector;
    }

    /// <summary>
    /// A blockmap of <paramref name="width"/> × <paramref name="height"/> blocks
    /// of 128 from the origin: each block lists (after the customary 0) the
    /// linedefs whose bounding box touches it, which is exact for these
    /// axis-aligned lines.
    /// </summary>
    private static byte[] BuildBlockmap(short originX, short originY, short width, short height, short[] vertexes, short[,] linedefs)
    {
        var offsets = new List<short> { originX, originY, width, height };
        var lists = new List<short>();
        int listStart = 4 + width * height;
        for (int by = 0; by < height; by++)
        {
            for (int bx = 0; bx < width; bx++)
            {
                offsets.Add((short)(listStart + lists.Count));
                int left = originX + bx * 128, bottom = originY + by * 128;
                lists.Add(0);
                for (int i = 0; i < linedefs.GetLength(0); i++)
                {
                    short v1 = linedefs[i, 0], v2 = linedefs[i, 1];
                    int x1 = vertexes[2 * v1], y1 = vertexes[2 * v1 + 1], x2 = vertexes[2 * v2], y2 = vertexes[2 * v2 + 1];
                    if (Math.Max(x1, x2) >= left && Math.Min(x1, x2) <= left + 128 && Math.Max(y1, y2) >= bottom && Math.Min(y1, y2) <= bottom + 128)
                        lists.Add((short)i);
                }
                lists.Add(-1);
            }
        }
        offsets.AddRange(lists);
        return Shorts([.. offsets]);
    }

    private static byte[] Concat(params byte[][] parts)
    {
        var all = new List<byte>();
        foreach (byte[] part in parts)
            all.AddRange(part);
        return [.. all];
    }

    private static byte[] Shorts(params short[] values)
    {
        byte[] data = new byte[values.Length * 2];
        for (int i = 0; i < values.Length; i++)
            BinaryPrimitives.WriteInt16LittleEndian(data.AsSpan(i * 2), values[i]);
        return data;
    }

    // ---- Other lumps ----

    private static byte[] BuildEndoom()
    {
        byte[] lump = new byte[80 * 25 * 2];
        string text = "IsoDoom synthetic test IWAD - generated content, no id Software data";
        for (int i = 0; i < 80 * 25; i++)
        {
            lump[i * 2] = (byte)' ';
            lump[i * 2 + 1] = 0x1F; // white on blue
        }
        int start = 12 * 80 + (80 - text.Length) / 2;
        for (int i = 0; i < text.Length; i++)
            lump[(start + i) * 2] = (byte)text[i];
        return lump;
    }

    private static byte[] BuildDemo()
    {
        // v1.9 header: version, skill, episode, map, deathmatch, respawn, fast, nomonsters, consoleplayer, playeringame[4].
        var demo = new List<byte> { 109, 2, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0 };
        for (int tic = 0; tic < 35; tic++)
            demo.AddRange([25, 0, (byte)(tic < 17 ? 2 : 0), 0]); // forwardmove, sidemove, angleturn, buttons
        demo.Add(0x80); // DEMOMARKER
        return [.. demo];
    }

    private static byte[] BuildGenmidi()
    {
        // "#OPL_II#", 175 genmidi_instr_t of 36 bytes, 175 names of 32 bytes (T7.8b). Every value is generated
        // here from the instrument's number (no id data): melodic instruments with varied operators, every
        // eighth one two-voice (detuned, an octave up), the 47 percussion instruments fixed-note.
        byte[] lump = new byte[Genmidi.FullSize];
        Encoding.ASCII.GetBytes(Genmidi.GENMIDI_HEADER, lump);
        for (int i = 0; i < Genmidi.NumInstruments; i++)
        {
            Span<byte> instr = lump.AsSpan(Genmidi.InstrumentsOffset + i * GenmidiInstrument.Size, GenmidiInstrument.Size);
            bool percussion = i >= Genmidi.GENMIDI_NUM_INSTRS;
            bool twoVoice = !percussion && i % 8 == 3;
            ushort flags = (ushort)((percussion ? Genmidi.GENMIDI_FLAG_FIXED : 0) | (twoVoice ? Genmidi.GENMIDI_FLAG_2VOICE : 0));
            BinaryPrimitives.WriteUInt16LittleEndian(instr, flags);
            instr[2] = (byte)(twoVoice ? 128 + 2 + i % 5 : 128); // fine tuning of the second voice (128: none)
            instr[3] = (byte)(percussion ? 24 + (i - Genmidi.GENMIDI_NUM_INSTRS) * 3 % 60 : 0); // fixed note
            WriteSyntheticVoice(instr[4..], i, 0);
            if (twoVoice)
                WriteSyntheticVoice(instr[(4 + GenmidiVoice.Size)..], i, 1);
            string name = percussion ? $"Synthetic drum {i - Genmidi.GENMIDI_NUM_INSTRS + Genmidi.PercussionFirstNote}" : $"Synthetic {i}";
            Encoding.ASCII.GetBytes(name, lump.AsSpan(Genmidi.NamesOffset + i * Genmidi.NameSize));
        }
        return lump;
    }

    // genmidi_voice_t: modulator (6 bytes: the 0x20, 0x60, 0x80, 0xE0 register values, key scale bits, level),
    // feedback/connection, carrier (6), unused, base note offset (signed 16-bit).
    private static void WriteSyntheticVoice(Span<byte> v, int i, int voice)
    {
        bool percussion = i >= Genmidi.GENMIDI_NUM_INSTRS;
        int k = i * 7 + voice * 3;
        v[0] = (byte)((k % 3 == 0 ? 0x40 : 0) | 0x20 | (1 + k % 4));         // modulator: vibrato every third, sustain, multiplier
        v[1] = (byte)(((percussion ? 15 : 8 + k % 8) << 4) | (2 + k % 6));    // attack, decay
        v[2] = (byte)(((k % 10) << 4) | (percussion ? 6 : 3 + k % 4));        // sustain level, release
        v[3] = (byte)(k % 4);                                                 // waveform
        v[4] = (byte)(0x40 * (k % 4));                                        // key scale level
        v[5] = (byte)(12 + k % 30);                                           // modulator level (its depth)
        v[6] = (byte)(((k % 7) << 1) | (!percussion && k % 5 == 0 ? 1 : 0));  // feedback, connection (1: additive)
        v[7] = (byte)(0x20 | (1 + k % 2));                                    // carrier
        v[8] = (byte)(((percussion ? 15 : 10 + k % 6) << 4) | (1 + k % 5));
        v[9] = (byte)(((k % 6) << 4) | (percussion ? 7 : 4 + k % 3));
        v[10] = (byte)(k % 9 == 0 ? 1 : 0);
        v[11] = 0;
        v[12] = (byte)(k % 6);                                                // carrier level (its loudness)
        v[13] = 0;
        short offset = (short)(voice == 1 ? 12 : !percussion && i % 12 == 0 ? -12 : 0);
        BinaryPrimitives.WriteInt16LittleEndian(v[14..], offset);
    }

    /// <summary>The synthetic song's (<c>D_E1M1</c>, T7.8b) length in tics: 16 steps of 35, a bend of 4 × 20, 200, 35.</summary>
    public const int SongTics = 16 * 35 + 4 * 20 + 200 + 35;

    /// <summary>The synthetic song's events, the score end included: 9 controllers, 80 in the steps, 7 at the end.</summary>
    public const int SongEvents = 9 + 80 + 7;

    private static byte[] BuildMus()
    {
        // MUS (T7.8b): a short generated song with every event kind mus2mid.c converts (play note with and
        // without a volume, release, pitch wheel, system event, controller changes: instrument, volume, pan,
        // expression), three melodic channels and the percussion channel, a delay of two bytes, then the score end.
        var score = new List<byte>();
        int last = -1;
        void Event(int type, int channel, params byte[] data)
        {
            last = score.Count;
            score.Add((byte)((type << 4) | channel));
            score.AddRange(data);
        }
        void Wait(int tics)
        {
            score[last] |= 0x80; // the group's last event: a delay follows
            if (tics >= 128)
                score.Add((byte)(0x80 | (tics >> 7)));
            score.Add((byte)(tics & 0x7F));
        }
        const int Release = 0, Press = 1, Pitch = 2, SystemEvent = 3, Controller = 4, ScoreEnd = 6, Drums = MusSong.PercussionChannel;

        Event(Controller, 0, 0, 33);  // bass: instrument 33
        Event(Controller, 0, 3, 110); // volume
        Event(Controller, 0, 4, 40);  // pan, left of the centre
        Event(Controller, 1, 0, 80);  // lead: instrument 80
        Event(Controller, 1, 3, 100);
        Event(Controller, 1, 4, 88);
        Event(Controller, 2, 0, 3);   // chords: instrument 3, a two-voice one
        Event(Controller, 2, 5, 90);  // expression
        Event(Controller, Drums, 3, 120);
        int[] roots = [36, 36, 41, 43];
        int[] arpeggio = [0, 4, 7, 12];
        for (int step = 0; step < 16; step++)
        {
            int root = roots[step / 4];
            int lead = root + 24 + arpeggio[step % 4];
            int drum = step % 4 == 2 ? 38 : step % 2 == 0 ? 35 : 42;
            if (step % 4 == 0)
            {
                Event(Press, 0, (byte)(0x80 | root), (byte)(90 + step)); // bass, with a volume
                Event(Press, 2, (byte)(0x80 | (root + 16)), 70);         // chord's third
            }
            if (step % 2 == 0)
                Event(Press, 1, (byte)(0x80 | lead), 110);
            else
                Event(Press, 1, (byte)lead); // no volume: the channel's last
            Event(Press, Drums, (byte)(0x80 | drum), (byte)(step % 4 == 0 ? 127 : 80));
            Wait(30);
            Event(Release, 1, (byte)lead);
            Event(Release, Drums, (byte)drum);
            if (step % 4 == 3)
            {
                Event(Release, 0, (byte)root);
                Event(Release, 2, (byte)(root + 16));
            }
            Wait(5);
        }
        // A long lead note bent up and back, released, all notes off, the score end.
        Event(Press, 1, 0x80 | 72, 100);
        Wait(20);
        Event(Pitch, 1, 160);
        Wait(20);
        Event(Pitch, 1, 192);
        Wait(20);
        Event(Pitch, 1, 128);
        Wait(20);
        Event(Release, 1, "H"u8.ToArray());
        Wait(200); // two delay bytes
        Event(SystemEvent, 1, 11); // all notes off
        Wait(35);
        Event(ScoreEnd, 0);

        ushort[] instruments = [3, 33, 80, 135, 138, 142]; // the programs, and the drums as percussion note + 100
        int start = MusSong.HeaderSize + 2 * instruments.Length;
        byte[] lump = new byte[start + score.Count];
        Encoding.ASCII.GetBytes("MUS\x1A", lump);
        BinaryPrimitives.WriteUInt16LittleEndian(lump.AsSpan(4), (ushort)score.Count);
        BinaryPrimitives.WriteUInt16LittleEndian(lump.AsSpan(6), (ushort)start);
        BinaryPrimitives.WriteUInt16LittleEndian(lump.AsSpan(8), 3); // primary channels
        BinaryPrimitives.WriteUInt16LittleEndian(lump.AsSpan(12), (ushort)instruments.Length);
        for (int i = 0; i < instruments.Length; i++)
            BinaryPrimitives.WriteUInt16LittleEndian(lump.AsSpan(MusSong.HeaderSize + 2 * i), instruments[i]);
        score.CopyTo(lump, start);
        return lump;
    }

    // D_INTRO: a type 1 MIDI file (Chocolate Doom plays a PWAD's MIDI lumps
    // through midifile.c, T7.8d): a tempo track changing the tempo mid-song,
    // a melodic track (program changes, volume, pan, pitch bends, running
    // status, a note on of velocity 0 as its note off, a SysEx and a text
    // event) and a percussion track (channel 10; one note outside GENMIDI's
    // 35-81), 96 ticks per quarter note.
    private static byte[] BuildMidi()
    {
        static void Vlq(List<byte> b, int v)
        {
            var groups = new List<byte> { (byte)(v & 0x7F) };
            while ((v >>= 7) != 0)
                groups.Insert(0, (byte)(0x80 | (v & 0x7F)));
            b.AddRange(groups);
        }
        static void Ev(List<byte> b, int delta, params byte[] bytes)
        {
            Vlq(b, delta);
            b.AddRange(bytes);
        }

        var tempo = new List<byte>();
        Ev(tempo, 0, 0xFF, 0x51, 3, 0x07, 0xA1, 0x20);    // 500000 us per beat
        Ev(tempo, 384, 0xFF, 0x51, 3, 0x06, 0x1A, 0x80);  // 400000
        Ev(tempo, 384, 0xFF, 0x51, 3, 0x09, 0x27, 0xC0);  // 600000
        Ev(tempo, 384, 0xFF, 0x2F, 0);

        var melody = new List<byte>();
        Ev(melody, 0, 0xFF, 0x01, 4, (byte)'t', (byte)'e', (byte)'s', (byte)'t');
        Ev(melody, 0, 0xC0, 19);                 // program 20
        Ev(melody, 0, 0xB0, 0x07, 100);          // volume
        Ev(melody, 0, 0x0A, 20);                 // pan (running status)
        Ev(melody, 0, 0xC1, 6);
        Ev(melody, 0, 0xB1, 0x0A, 110);
        int[] scale = [60, 62, 64, 65, 67, 69, 71, 72];
        for (int i = 0; i < scale.Length; i++)
        {
            Ev(melody, i == 0 ? 0 : 48, 0x90, (byte)scale[i], (byte)(70 + 7 * i));
            Ev(melody, 0, 0x91, (byte)(scale[i] - 12), 90);
            if (i == 3)
                Ev(melody, 24, 0xE0, 0x00, 0x50);     // bend up
            if (i == 4)
                Ev(melody, 24, 0xE0, 0x00, 0x40);     // and back
            if (i == 5)
                Ev(melody, 0, 0xF0, 3, 0x7E, 0x7F, 0xF7); // SysEx
            if (i == 6)
                Ev(melody, 0, 0xB0, 0x0A, 64);       // pan centre
            Ev(melody, i is 3 or 4 ? 24 : 48, 0x90, (byte)scale[i], 0);  // velocity 0: off
            Ev(melody, 0, 0x81, (byte)(scale[i] - 12), 0);
        }
        Ev(melody, 0, 0xB1, 0x7B, 0);            // all notes off
        Ev(melody, 0, 0xFF, 0x2F, 0);

        var drums = new List<byte>();
        byte[] kit = [36, 42, 38, 42, 30, 42, 38, 81];
        for (int i = 0; i < 16; i++)
        {
            Ev(drums, i == 0 ? 0 : 36, 0x99, kit[i % kit.Length], 110);
            Ev(drums, 36, 0x89, kit[i % kit.Length], 0);
        }
        Ev(drums, 0, 0xFF, 0x2F, 0);

        var midi = new List<byte>();
        midi.AddRange(Encoding.ASCII.GetBytes("MThd"));
        midi.AddRange([0, 0, 0, 6, 0, 1, 0, 3, 0, 96]); // format 1, 3 tracks, 96 ticks per quarter
        foreach (List<byte> track in new[] { tempo, melody, drums })
        {
            midi.AddRange(Encoding.ASCII.GetBytes("MTrk"));
            midi.AddRange([0, 0, (byte)(track.Count >> 8), (byte)track.Count]);
            midi.AddRange(track);
        }
        return [.. midi];
    }

    private static byte[] BuildDmxSound()
    {
        // DMX: format 3, 11025 Hz, sample count (incl. the 16 pad bytes either side), then 8-bit unsigned samples.
        const int Samples = 2048;
        byte[] lump = new byte[8 + 16 + Samples + 16];
        BinaryPrimitives.WriteUInt16LittleEndian(lump, 3);
        BinaryPrimitives.WriteUInt16LittleEndian(lump.AsSpan(2), 11025);
        BinaryPrimitives.WriteUInt32LittleEndian(lump.AsSpan(4), Samples + 32);
        for (int i = 0; i < 16; i++)
        {
            lump[8 + i] = 128;
            lump[8 + 16 + Samples + i] = 128;
        }
        for (int i = 0; i < Samples; i++)
        {
            int amplitude = 100 * (Samples - i) / Samples;
            lump[8 + 16 + i] = (byte)(128 + ((i / 12) % 2 == 0 ? amplitude : -amplitude)); // decaying square wave
        }
        return lump;
    }

    private static byte[] BuildPcSpeakerSound()
    {
        // PC speaker: format 0, tone count, then one tone byte per 1/140 s.
        byte[] lump = new byte[4 + 20];
        BinaryPrimitives.WriteUInt16LittleEndian(lump.AsSpan(2), 20);
        for (int i = 0; i < 20; i++)
            lump[4 + i] = (byte)(60 - i * 2);
        return lump;
    }

    // ---- WAD writer ----

    private sealed class Writer
    {
        private readonly List<(string Name, byte[] Data)> _lumps = [];

        public void Lump(string name, byte[]? data = null) => _lumps.Add((name, data ?? []));

        public void Markers(params string[] names)
        {
            foreach (string name in names)
                Lump(name);
        }

        /// <summary>Header, lump data, then the directory (as id's tools lay it out).</summary>
        public byte[] Build()
        {
            int dataSize = 0;
            foreach ((_, byte[] data) in _lumps)
                dataSize += data.Length;
            byte[] wad = new byte[12 + dataSize + 16 * _lumps.Count];
            Encoding.ASCII.GetBytes("IWAD", wad);
            BinaryPrimitives.WriteInt32LittleEndian(wad.AsSpan(4), _lumps.Count);
            BinaryPrimitives.WriteInt32LittleEndian(wad.AsSpan(8), 12 + dataSize);
            int pos = 12;
            for (int i = 0; i < _lumps.Count; i++)
            {
                (string name, byte[] data) = _lumps[i];
                if (name.Length > 8)
                    throw new InvalidOperationException($"Lump name {name} is longer than 8 characters.");
                data.CopyTo(wad, pos);
                Span<byte> entry = wad.AsSpan(12 + dataSize + 16 * i, 16);
                BinaryPrimitives.WriteInt32LittleEndian(entry, data.Length == 0 ? 0 : pos);
                BinaryPrimitives.WriteInt32LittleEndian(entry[4..], data.Length);
                Encoding.ASCII.GetBytes(name, entry[8..]);
                pos += data.Length;
            }
            return wad;
        }
    }
}
